### ISSUE TITLE
multiple/group Diffie-Hellman

### ISSUE THREAD

**Issue by pohutukawa** [indutny/elliptic#1]
I was wondering whether this library allows for triple or group Diffie-Hellman operations, where multiple scalar multiplications are required of the base point with several keys. 

Similar to what `computeKey()` does in jodid25519:

https://github.com/meganz/jodid25519/blob/master/src/jodid25519/dh.js#L72

It would be interesting to be able to compare elliptic and jodid25519 side-by-side this way.

**Comment by indutny** [comment]
Sorry, no progress here, and it doesn't look like I will have time to work on it. I suggest opening another issue if this is still concerns you. Thanks!
