### ISSUE TITLE
Add support for multiplying points with BigInts in reduction context

### ISSUE THREAD

**Issue by kripod** [indutny/elliptic#101]

**Comment by indutny** [comment]
@kripod is it a note to yourself? The issue is clearly missing description/motivation/etc.

**Comment by kripod** [comment]
The motivation is lazyness 😂

It would be great if no conversion was needed to multiply a `Point` with a `BigInt` in reduction context. Just add a check for `BigInt#isRed` and convert the given `BigInt` if necessary.

**Comment by indutny** [comment]
@kripod why not convert it before passing to `elliptic`? I can add an assert that will check that the number is not in reduction context. I'm not a huge supporter of extending API's input types.

**Comment by kripod** [comment]
I'm currently converting it before passing it to `elliptic`, but that isn't so convenient. Also, isn't point multiplication optimizable when using a reduction context?

**Comment by indutny** [comment]
There is no performance benefit, and in fact `elliptic` **needs** them to be converted out of the reduction context. Sorry, but won't fix.

**Comment by kripod** [comment]
Nevermind, thank you for the review!
