### ISSUE TITLE
verifying base64 signatures

### ISSUE THREAD

**Issue by daavidjobe** [indutny/elliptic#103]
##Hello,

I´m a beginner at this so please bare with me =)

I´m creating signatures (using the same curve) in a java back-end and now I would like to verify them on the client. I can only access a base64 encoded string of the signature and this presents some obstacles with verifying. I used a solution from another issue posted here which got rid of errors but still, the verification fails.

Any idea why?

`key: 02b9fbe03db3e1e057538bd4b03c34ab3f419336e2a97ca5c356ad4f3feb266dbb`
`signature: MEQCIH6Y4uiZE1czviUYYwjAhyvYcWuX+....`
`message: f8e77c50....`

```javascript

const ec = new elliptic.ec('secp256k1')

 const asDer = signature => {
    const signatureHex = new Buffer(signature).toString('hex')
    const m = signatureHex.match(/([a-f\d]{64})/gi)
    return {
      r: m[0], s: m[1]
    }
  }

 const verifySignature = (message, publicKey, signature) => {
    const key = ec.keyFromPublic(publicKey, 'hex')
    console.log(asDer(signature))
    return ec.verify(message, asDer(signature), publicKey, 'hex')
  }
```

Thank you

**Comment by indutny** [comment]
@daavidjobe hello! Have you tried `new Buffer(signature, 'base64')`? There should be no need to split it into parts after that.

**Comment by daavidjobe** [comment]
Oh my god. You're a life saver. Thought I tried that but obviously I did not. Thank you!

**Comment by wellingtonsampaio** [comment]
@daavidjobe @indutny I am facing an issue related to this. I have a ec signature (r and s) which can be converted to DER (signature.toDER()). How can I convert the signature to base64?
