### ISSUE TITLE
Browserified package contains full package path

### ISSUE THREAD

**Issue by scholtzm** [indutny/elliptic#106]
```
$ npm list elliptic
└─┬ browserify@13.0.1
  └─┬ crypto-browserify@3.11.0
    └─┬ browserify-sign@4.0.0
      └── elliptic@6.3.1
```

After creating bundle via browserify, full package path is exposed directly in the bundle.

This is caused by 2 things:
1. [Requiring package.json.](https://github.com/indutny/elliptic/blob/master/lib/elliptic.js#L5)
2. Once the package is installed, extra fields are added into package.json such as `_where` - this value contains full path to parent/dependent package.

It's not a huge deal but disclosing folder structure is far from ideal.

**Comment by fanatid** [comment]
@scholtzm thank you that pointed on this. Personally I ever never thought that bundle can contain personal information. Any ideas how this can be solved? (Except doubling version in two places)

**Comment by fanatid** [comment]
@scholtzm I found solution for you.
Check https://github.com/nolanlawson/package-json-versionify or https://github.com/fanatid/browserify-package-json
(but you need pass option global equal true to transform)

We also can use https://github.com/webpro/versionify but I think it's shitty solution.

@indutny we can close this issue.

**Comment by scholtzm** [comment]
Sorry for not replying. As a quick fix, I just added a post-process step which would remove the file path from the final bundle we are shipping.

Seems like `package-json-versionify` is spot on solution for this problem and I'll use it. Thanks.

**Comment by fanatid** [comment]
Be careful with `package-json-versionify` because this package remove all except `version`.

**Comment by lorem--ipsum** [comment]
This is still an issue, we're using ellptic through webpack and `elliptic/lib/elliptic.js:5` requires the package.json file to access its version number, which results in  packaging the entire file in the output JavaScript. I don't think it's a webpack/browserify issue though...
