### ISSUE TITLE
How can I use Curve25519/Ed25519 to do encryption?

### ISSUE THREAD

**Issue by DonaldTsang** [indutny/elliptic#108]
For my personal project, I am using an ECC+AES combo to create a PGP-like cipher, where I use a public key to encrypt a symmetric key, of which the receiver uses the private key to unlock the symmetric key encrypted text.

How can I do that using your module?

**Comment by fanatid** [comment]
Maybe I don't understand something, but how you encrypt symmetric key with public key and how this protect encrypted message from 3rd persons who also knew public key?

**Comment by DonaldTsang** [comment]
Because it takes the private key to retrieve the symmetric key, and it takes the symmetric key to retrieve the message.

**Comment by fanatid** [comment]
Okay, can you describe how you encrypt symmetric key with public key and decrypt symmetric key with private key?

**Comment by DonaldTsang** [comment]
From my knowledge of other asymmetric ciphers (RSA), you basically have:
Ciphertext = Encryption(Plaintext, Public-exponent/Public-key, Modulo/Curve)
Plaintext = Decryption(Ciphertext, Private-exponent/Private-key, Modulo/Curve)

**Comment by fanatid** [comment]
[ECC](https://en.wikipedia.org/wiki/Elliptic_curve_cryptography) is not RSA-like cryptosystem, please read about [ECDH](https://en.wikipedia.org/wiki/Elliptic_curve_Diffie%E2%80%93Hellman) and [ECIES](https://en.wikipedia.org/wiki/Integrated_Encryption_Scheme).

**Comment by indutny** [comment]
@DonaldTsang I'm afraid that ECC by itself is not suitable for encryption, just signature/verification.

**Comment by DonaldTsang** [comment]
Is there a way to implement ECIES without the MAC component?
My twitter cipher already has unchangeable name tags, so i don't want to waste space on MACs.
I only need it to function like PGP (since PGP has this symmetric-asymmetric combo)

**Comment by DonaldTsang** [comment]
Key Pair Generation and other info
PrivKey is between 1 and n-1 (An integer only the reciever knows)
PubKey = PrivKey * G (A point that the public knows)
Salt (Not yet known if its only the reciever or for anyone)

Encryption
Random r is between 1 and n-1
R = r * G (A point)
P = r * PubKey (A point)
P = (P_x, P_y)
SymKey = KDF(P_x || Salt)
CipherText = Encrypt(SymKey, PlainText)
Output R and CipherText

Decryption
P = PrivKey * R (A point)
P = (P_x, P_y)
SymKey = KDF(P_x || Salt)
PlainText = Decrypt(SymKey, cipherText)

Reasoning
P = r * PubKey = PrivKey * R, since that
P = r * (PrivKey * G) = PrivKey * (r * G)

KDF library
KDF can be scrypt (js-scrypt)
or it can be pbkdf2 (cryptojs)

**Comment by fanatid** [comment]
@DonaldTsang is your issue is resolved now?

**Comment by DonaldTsang** [comment]
@fanatid I need some help to implement though.

**Comment by DonaldTsang** [comment]
@fanatid @indutny Three questions:
1. How do I generate a random integer in the range of [1,n-1]?
2. How do I multiply a random integer to the base point of Curve25519?
3. When I do key1.derive(key2.getPublic()), Is key1 the private key and key2 the public key?

**Comment by fanatid** [comment]
1. elliptic uses [bn.js](https://github.com/indutny/bn.js). You can generate number with [crypto.randomBytes](https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback) and then check interval (0, n). Or you can use `.getKeyPair()`
2. `new EC('curve25519').g.mul`
3. You're right.

example with custom random generator and base point multiplication
```js
const crypto = require('crypto')
const BN = require('bn.js')
const EC = require('elliptic').ec

const curve = new EC('curve25519')
let privateKey
do {
  privateKey = new BN(crypto.randomBytes(Math.ceil(curve.n.bitLength() / 8)))
} while (privateKey.isZero() || privateKey.cmp(curve.n) >= 0)

const publicKey = curve.g.mul(privateKey)
```

multiplcation example:
```js
const EC = require('elliptic').ec
const curve = new EC('curve25519')

const pair1 = curve.genKeyPair()
const pair2 = curve.genKeyPair()

console.log(pair1.derive(pair2.getPublic()))
console.log(pair2.derive(pair1.getPublic()))
// should be same
```

**Comment by DonaldTsang** [comment]
Could you have a look at what is wrong in my code?
`
var ECDH = require('elliptic').ec;
var ec = new ECDH('curve25519');

var key = ec.genKeyPair();
pub = key.getPublic(); // shown to public in list
priv = key.getPrivate(); // hidden in private userbase

var rand = ec.genKeyPair();
r = rand.getPublic(); // shown to public in message
x = rand.getPrivate().derive(pub) // the secret password
// rand and x is discarded after the message is sent
y = priv.derive(r)
colsole.log(x === y)
`

**Comment by fanatid** [comment]
`.getPrivate()` return BN instance (bn.js), you need derive from key pair:

fixed example:
```js
var ECDH = require('elliptic').ec;
var ec = new ECDH('curve25519');

var key = ec.genKeyPair();
pub = key.getPublic(); // shown to public in list
priv = key.getPrivate(); // hidden in private userbase

var rand = ec.genKeyPair();
r = rand.getPublic(); // shown to public in message

x = rand.derive(pub) // the secret password
y = key.derive(r)
colsole.log(x.cmp(y) === 0)
```

**Comment by DonaldTsang** [comment]
What if I want a function that give out the same result as  `key.derive(r)` without using the whole key-pair `key` and instead use `priv`?

**Comment by fanatid** [comment]
Please read source code, it's all easy..
```js
const crypto = require('crypto')
const BN = require('bn.js')
const EC = require('elliptic').ec

const curve = new EC('curve25519')

const genKey = () => {
  while (true) {
    const privateKey = new BN(crypto.randomBytes(Math.ceil(curve.n.bitLength() / 8)))
    if (!privateKey.isZero() && privateKey.cmp(curve.n) < 0) return privateKey
  }
}

const key1 = genKey()
const key2 = genKey()

// curve.g.mul(key) -- publicKey
const shared1 = curve.g.mul(key1).mul(key2).getX()
const shared2 = curve.g.mul(key2).mul(key1).getX()

// 32 enough for curve25519
console.log(shared1.toArrayLike(Buffer, 'be', 32))
console.log(shared2.toArrayLike(Buffer, 'be', 32))
// => shared1 should be equal shared2
```

**Comment by DonaldTsang** [comment]
For my personal project, I will include `https://github.com/indutny/elliptic/blob/master/dist/elliptic.min.js` in my html `<script>`, does that mean I don't need `crypto` and `BN`?

**Comment by fanatid** [comment]
Of couse you need `crypto` and `BN` in that case.
But you also can use `hmacDRBG` from `elliptic` and extract `BN` from `elliptic` build.

`require('elliptic').curves.curve25519.n.constructor` gives you BN constructor, but it is not good way

**Comment by DonaldTsang** [comment]
But I am not using Node.js on my html project, can I use "require" without node.js?

**Comment by DonaldTsang** [comment]
Also, assume that I am using only curve25519, can I translate pure public key and pure private key from EC's `.getPublic()` and `.getPrivate()` format to byte strings and back using key Recovery?

**Comment by DonaldTsang** [comment]
@fanatid so how do I import and export private and public key as hex?
(And why is the private key have variable length between 62 and 64 hex?)
```
var ec = new elliptic.ec('curve25519');

function keyGen () {
	var key = ec.genKeyPair();
	pub = key.getPublic(); // shown to public in list
	pubHex = key.getPublic('hex');
	priv = key.getPrivate(); // hidden in private userbase
	privHex = key.getPrivate('hex');
	return [key, pub, pubHex, priv, privHex]
}

function randGen () {
	var rand = ec.genKeyPair();
	r = rand.getPublic(); // shown to public in message
	rHex = rand.getPublic('hex');
	return [rand, r, rHex]
}

function secret (pub, priv) {return priv.derive(pub)}

function compare (x, y) {return x.cmp(y) === 0}

[key, pub, pubHex, priv, privHex] = keyGen();
[rand, r, rHex] = randGen();

pubHexBack = keyFromPrivate(pub, 'hex')
privHexBack = keyFromPublic(priv, 'hex')
rHexBack = keyFromPublic(r, 'hex')

x = rand.derive(pub) // the secret password
y = key.derive(r)

v = rand.derive(pubHexBack)
w = privHexBack.derive(rHexBack)
console.log(compare(x, y))
console.log(compare(v, w))
```

**Comment by oberien** [comment]
For ECIES based on elliptic you could use [eccrypto](https://github.com/bitchan/eccrypto), but you need to modify it to use `curve25519` instead of `secp256k1`.

To answer your particular question:
The private key is just a completely random number. It can theoretically have an arbitrary length <= 64 hex.
For `curve25519` exporting wtih `getPrivate("hex")` and `getPublic("hex")` work fine. For importing `keyFromPrivate(priv, "hex")` and `keyFromPublic(pub, "hex")` are the way to go. In your example you are using `keyFromPrivate` to get the public key and `keyFromPublic` to get the private key, which is exactly the other way around.
