### ISSUE TITLE
Error: Webpack compiling

### ISSUE THREAD

**Issue by microshine** [indutny/elliptic#109]
I'm trying to compile my project `webcrypto-liner`, which has dependecy of `elliptic`. But I've got a error on webpack compiling in [elliptic.js](https://github.com/indutny/elliptic/blob/master/lib/elliptic.js#L5)

```
ERROR in ./~/elliptic/package.json
Module parse failed: C:\github\webcrypto-liner\node_modules\elliptic\package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp$4.raise 
    at Parser.pp.unexpected 
    at Parser.pp.semicolon 
    at Parser.pp$1.parseExpressionStatement 
    ...
@ ./~/elliptic/lib/elliptic.js 5:19-45
```

**Comment by fanatid** [comment]
@microshine why not create issue in [webpack repository](https://github.com/webpack/webpack)?

**Comment by swansontec** [comment]
You need to fix your webpack config:

    loaders: [
      { test: /\.json$/, loader: 'json-loader' }
    ]

And add `json-loader` to your `devDependencies` in `package.json`.

**Comment by microshine** [comment]
thank you. It works for me
