### ISSUE TITLE
Curve25519 private key is not the one set

### ISSUE THREAD

**Issue by Ayms** [indutny/elliptic#111]
Probably missing something or doing something incorrect, the context is an adaptation of [bitcoin-wallets](https://github.com/Ayms/bitcoin-wallets) for Zcash, not an expert in curve25519, reference is section 4.2 of https://github.com/zcash/zips/blob/master/protocol/protocol.pdf

The code is simply:

````javascript
var ECDH=require('elliptic').ec;
var ecdh=new ECDH('curve25519');
var FormatPrivate=function(buf) {
	buf[0] &=0xf8;
	buf[31] &=0x7f;
	buf[31] |=0x40;
	return buf;
};
var sk_enc='f80f6ed0d1ad1dd2252ff4cd2a366174fb30580c21d86722c48513fcd4646963'; (after FormatPrivate, initial vector was  fc0f6ed0d1ad1dd2252ff4cd2a366174fb30580c21d86722c48513fcd4646963)
var key=ecdh.keyFromPrivate(sk_enc);
//key.priv=new BN(sk_enc);
console.log(key.getPrivate('hex'));
//080f6ed0d1ad1dd2252ff4cd2a366173c21fb400955636939b71457161fcfe80
//not the same
console.log(new Buffer(key.getPublic(true,'arr'),'hex'));
//2b28a340d90aba1a37c69481f06540fe3956963400e198cfa16c65af6c37a2c0
//Not what is expected
````
Uncommenting key.priv leads to the same public key, so maybe the formats are just equivalent but this is not the expected public key (might be a misimplementation of the specs from myself but would like to be sure that I am using elliptic correctly)

**Comment by fanatid** [comment]
@Ayms why you're saying that result is incorrect?

**Comment by Ayms** [comment]
Because unless I did not implement correctly Zcash derivation calculation for pk_enc (which is not unlikely at all) I should get the reverse of ``<Buffer 21 ec 35 6c c1 20 5d 28 5c 73 29 7e fd ff 9d 7d 51 fa ba 88 1e 98 06 98 09 db e2 71 8f 48 50 a2>``

Unfortunately I could not find any Curve25519 implementation that I could use to check against elliptic, so sorry if the outcome is trivial but would at least like to know if the above use/behavior/results are correct

**Comment by fanatid** [comment]
can you give link to code/docs with private key and derivation result?

**Comment by Ayms** [comment]
See 4.2 in https://github.com/zcash/zips/blob/master/protocol/protocol.pdf and then 5.4.4 for PRF function, 5.4.6 for FormatPrivate (same than https://github.com/agl/curve25519-donna) then seek for DerivePublic in the document, as far as I understand this is the ecdh Curve25519 public key corresonding to the skenc private key.

FYI, I have modified SHA-256 to implement in js SHA256Compress for the PRF function, this is working for apk key, might have some bugs but I don't think for that one

**Comment by Ayms** [comment]
For this example, sk is ``<Buffer 06 5e 8e d4 45 c3 e6 45 63 20 73 53 48 c9 83 5a 3e 72 65 de 13 65 5c 54 9d bd bc e2 ad 0d ec 2d>``

**Comment by fanatid** [comment]
`key.getPrivate('hex')` return not same value because initial secret key is more then N value (I wrote about it in other issue https://github.com/indutny/elliptic/issues/98)
I did not seen any keys in 4.2 and don't see in 5.4.4/5.4.6

**Comment by Ayms** [comment]
Wow, it's unclear in the spec but you have to revert the result of SHA256Compress, then the correct code is:

````
var key=ecdh.keyFromPrivate(reverse('f80f6ed0d1ad1dd2252ff4cd2a366174fb30580c21d86722c48513fcd4646963'));
console.log(key.getPrivate('hex'));
//036964d4fc1385c42267d8210c5830faf7275af2fc26821fc1af5b33a2ab186a
//not the same but as far as I understand there is a modulo somewhere
console.log(new Buffer(key.getPublic(true,'arr'),'hex'));
//21ec356cc1205d285c73297efdff9d7d51faba881e98069809dbe2718f4850a2
//correct expected result
````

Thanks, closing it (definitely we can't say that crypto money world and formats make things easy...)

**Comment by fanatid** [comment]
I think you should write about reverse to ZCash team ;)

**Comment by Ayms** [comment]
Maybe but I don't want to frustrate them from the pleasure they apparently have (as well as bitcoin and probably other crypto moneys) to mix BE and LE all along the protocol :-)

**Comment by Ayms** [comment]
@fanatid FYI https://github.com/Ayms/zcash-wallets
