### ISSUE TITLE
Can I sign different messages with the same public key?

### ISSUE THREAD

**Issue by MaiaVictor** [indutny/elliptic#118]
As stated on the README, elliptic uses deterministic signatures. Doesn't that mean that `k` is always constant and, thus, signing two different messages with the same private key would immediately reveal it? What is the correct way to sign messages using this lib?

**Comment by fanatid** [comment]
@MaiaVictor check [Implementation details](https://github.com/indutny/elliptic#implementation-details).. `k` is not constant, this number generated by RFC6979

**Comment by indutny** [comment]
`k` is unique for each message+key combination.
