### ISSUE TITLE
Set specific public and private keys

### ISSUE THREAD

**Issue by tomhallam** [indutny/elliptic#127]
Hi,

What is the way to supply a specific hex public or private key for use in this library? I notice that anything I supply seems to be "bit shifted" (paraphrased from DJB's code) - at least I think that's the problem.

```
  e[0] &= 248;
  e[31] &= 127;
  e[31] |= 64;
```
... is there a specific way to achieve this properly, using this library?

At the moment I'm doing something like:

`const publicKey = ec.keyFromPublic(this.publicKey);`

and

`const privKey = ec.keyFromPrivate(this.privateKey);`

But this doesn't work - see the below example:

```
  verifyKeys() {

    const assert = require('assert');
    const ecdh = new require('elliptic').ec('curve25519');

    var s1 = ecdh.genKeyPair();
    var s2 = ecdh.genKeyPair();

    var sh1 = s1.derive(ecdh.keyFromPublic(this.publicKey)
                            .getPublic());

    var sh2 = s2.derive(ecdh.keyFromPublic(this.publicKey)
                            .getPublic());

    assert.equal(sh1.toString(16), sh2.toString(16));

  }
```

This returns an AssertionError as the values *do not match*.

Can anyone help?
Cheers

**Comment by indutny** [comment]
@tomhallam hello! Perhaps you may want to use `eddsa` API provided by this module? :wink:

**Comment by tomhallam** [comment]
@indutny thanks for your reply - but no, I'd like to derive a shared secret, which `eddsa` doesn't provide?

**Comment by indutny** [comment]
Oh right, sorry!

I think you may try something like what you posted. This should work more or less.

**Comment by tomhallam** [comment]
Can you think of why my code containing the assertion fails? It seems like that should work..? I've been looking at the problem for a while but have been unable to debug.

**Comment by indutny** [comment]
Sorry, haven't got time to look into it deeply until now.

I believe that your code fails because it is just doing the wrong thing. How are these values are supposed to be equal? In pseudo code:

```
publicKey = loadSomeKey()

s1 = randomKeyPair()
s2 = randomKeyPair()

s1.derive(publicKey) != s2.derive(publicKey)
```

This is pretty much normal. In common-sense algebra you are generating two random values and multiplying them by non-random value. The result will always be different.

**Comment by tomhallam** [comment]
@indutny apologies, I thought it would be a valid test case given one of your tests (https://github.com/indutny/elliptic/blob/master/test/ecdh-test.js) but after I reviewed it, of course it wouldn't work, so thanks for providing another pair of eyes.

However, the fact remains when I push a hex public/private key into `elliptic` using the `keyFrom*` commands, it seems to be changing it when it dump it out again using `publicKey.getPublic('hex')`. I'm not sure how to stop this behaviour, can you think of why it's doing this?

**Comment by tomhallam** [comment]
@indutny  To explore this behaviour further, I wrote a simple piece of code:

```javascript
    console.log('Random Public Key (pk) (crypto.randomBytes(32)):');
    const pk = crypto.randomBytes(32);
    console.log(pk.toString('hex'));

    console.log("\n" + 'Result of elliptic.keyFromPublic(pk, "hex").getPublic("hex"):');
    console.log(ec.keyFromPublic(pk, 'hex').getPublic('hex'));
```

Here were the outputs:

**Run 1 - Fine**

```
Random Public Key (pk) (crypto.randomBytes(32))
19cc652ac376f892170e0e3cbf90dda059574b13ac9c52a0e557faaa00169ca2

Result of elliptic.keyFromPublic(pk, "hex").getPublic("hex")
19cc652ac376f892170e0e3cbf90dda059574b13ac9c52a0e557faaa00169ca2
```

**Run 2 - Fine**

```
Random Public Key (pk) (crypto.randomBytes(32)):
70cb725f3e7ac8be653c314ca871e5b766e85f2e56e51a1f8ce549cf5a7708a8

Result of elliptic.keyFromPublic(pk, "hex").getPublic("hex"):
70cb725f3e7ac8be653c314ca871e5b766e85f2e56e51a1f8ce549cf5a7708a8
```

**Run 3 - Some sort of overflow?**

```
Random Public Key (pk) (crypto.randomBytes(32)):
d10b3aa808ce9606c048859dde83ed2450d352412dfce19a1b31f50202ca2384

Result of elliptic.keyFromPublic(pk, "hex").getPublic("hex"):
510b3aa808ce9606c048859dde83ed2450d352412dfce19a1b31f50202ca2397
```

**Run 4 - Again, another overflow?**

```
Random Public Key (pk) (crypto.randomBytes(32)):
a917637cc52a84ed54ad0f6e1fbb8bd1f403236dd262cd616e1414869aebd7d7

Result of elliptic.keyFromPublic(pk, "hex").getPublic("hex"):
2917637cc52a84ed54ad0f6e1fbb8bd1f403236dd262cd616e1414869aebd7ea
```

Shouldn't it be the same coming out of the library as going in or am I missing something?

**Comment by indutny** [comment]
No, it shoudn't. The public key is not just some random data, it is a point on Elliptic Curve. At the very least it has to be a number on a prime field, which means that it can't be bigger than:

```
7fffffffffffffff ffffffffffffffff ffffffffffffffff ffffffffffffffed
```

**Comment by tomhallam** [comment]
Thank you for your time, I've been learning as I've been going here and your responses have been valuable. I've managed to resolve my issue.

**Comment by indutny** [comment]
Hooray!
