### ISSUE TITLE
Public Key from String

### ISSUE THREAD

**Issue by ccravens** [indutny/elliptic#138]
I'm trying to generate a shared key from a public key that I get as a string. I'm trying to use the keyFromPublic(str, 'hex') method, but I get the following error:

```javascript
bundle.js:7077 Uncaught Error: Unknown point format
    at ShortCurve.decodePoint (bundle.js:7077)
    at KeyPair._importPublic (bundle.js:9284)
```

This is what my code looks like:

```javascript
ec.keyFromPublic('22B553039ED556E27DDFFCD9AC6F5411E966CFB7C26438ABDCE723692E7C69A06993A851A120326BE27299BA7D5128BC510C95132EF3CE2D6366CEA02E79A9EA','hex');
```

What is the correct way to generate a key from a public key provided as a string of hex characters?

**Comment by ccravens** [comment]
I was able to resolve the issue by adding a 04 to the front of the public key:

```javascript
ec.keyFromPublic('0422B553039ED556E27DDFFCD9AC6F5411E966CFB7C26438ABDCE723692E7C69A06993A851A120326BE27299BA7D5128BC510C95132EF3CE2D6366CEA02E79A9EA','hex');
```

**Comment by masoud2011** [comment]
> I was able to resolve the issue by adding a 04 to the front of the public key:
> 
> ```js
> ec.keyFromPublic('0422B553039ED556E27DDFFCD9AC6F5411E966CFB7C26438ABDCE723692E7C69A06993A851A120326BE27299BA7D5128BC510C95132EF3CE2D6366CEA02E79A9EA','hex');
> ```
Thanks, that helped me,
I had generated my private and public key in Arduino via uecc library. To testing it in node.js I had to add 04 at beginning like you, but I had to cut it to 130 characters too. because generated public in uecc was 800 characters.

**Comment by VictorNS69** [comment]
> I was able to resolve the issue by adding a 04 to the front of the public key:
> 
> ```js
> ec.keyFromPublic('0422B553039ED556E27DDFFCD9AC6F5411E966CFB7C26438ABDCE723692E7C69A06993A851A120326BE27299BA7D5128BC510C95132EF3CE2D6366CEA02E79A9EA','hex');
> ```
Hi! This worked and helped me a lot.

But I really don't understand why the `04`. Can you explain why this is needed?
Thanks!

**Comment by fanatid** [comment]
`04` means uncompressed key (`x` and `y`, both defined)
https://github.com/indutny/elliptic/blob/v6.5.2/lib/elliptic/curve/base.js#L271

**Comment by VictorNS69** [comment]
> `04` means uncompressed key (`x` and `y`, both defined)
> https://github.com/indutny/elliptic/blob/v6.5.2/lib/elliptic/curve/base.js#L271

Thanks a lot!
