### ISSUE TITLE
Elliptic (Nodejs) is unable to verify digital signature signed in Java.

### ISSUE THREAD

**Issue by eddywm** [indutny/elliptic#139]
I am building a java client application that will use a nodejs server for digital signatures verification.
I am currently failing to verify digital signatures signed in java in Nodejs (It is returning false all the time).

An example of interop between java and Nodejs (Elliptic Library) for ecdsa  is really needed here. 

## Java signing code.

```import org.bouncycastle.jce.provider.BouncyCastleProvider;

import javax.xml.bind.DatatypeConverter;
import java.io.UnsupportedEncodingException;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.security.spec.ECGenParameterSpec;

public class A {

public static void main(String[] args) throws NoSuchAlgorithmException, InvalidAlgorithmParameterException, InvalidKeyException, UnsupportedEncodingException, NoSuchProviderException, SignatureException {

        Security.addProvider(new BouncyCastleProvider());

        MessageDigest sha256Digest = MessageDigest.getInstance("SHA-256");

        KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance("ECDSA", "BC");

        ECGenParameterSpec ecGenParameterSpec = new ECGenParameterSpec("secp256k1");

        SecureRandom random = SecureRandom.getInstance("SHA1PRNG");

        keyPairGenerator.initialize(ecGenParameterSpec, random);

        KeyPair keyPair = keyPairGenerator.genKeyPair();

        PrivateKey privateKey = keyPair.getPrivate();

        PublicKey publicKey = keyPair.getPublic();



        System.out.println("Public Key: "+ publicKey  + "\n\n");


        Signature signature = Signature.getInstance("ECDSA", "BC");
        signature.initSign(privateKey, new SecureRandom());

        byte[] hashedMessage = sha256Digest.digest("This is the message".getBytes(StandardCharsets.UTF_8));


        signature.update(hashedMessage);

        byte[] signatureBytes = signature.sign();


        System.out.println("Original Message in hex: "+ DatatypeConverter.printHexBinary("This is the message".getBytes(StandardCharsets.UTF_8)));

        System.out.println("SHA256 Hashed Message in Hex: "+ DatatypeConverter.printHexBinary(hashedMessage)  + "\n\n");


        System.out.println("Signature: "+ DatatypeConverter.printHexBinary(signatureBytes) + "\n\n");



        System.out.println("Private Key ->  : " +  DatatypeConverter.printHexBinary(privateKey.getEncoded()));
        System.out.println("Public Key ->  :  " +DatatypeConverter.printHexBinary(publicKey.getEncoded()));



    }
}
```

## Output

```
Public Key: EC Public Key [1f:aa:2f:fe:55:f5:a6:a5:da:a9:ac:cb:7e:0f:23:25:07:db:6e:70]
            X: e5518c2d0fa9af8c6febf3b0142afdbca26f4ae08aca9a82199cbc4292b5697e
            Y: 6dafb1c949beff8e943b95eb7de5a49dc65de374b1707c675d15e8929207b3fe



Original Message in hex: 5468697320697320746865206D657373616765
SHA256 Hashed Message in Hex: C8ED5E65713F8170B8D0769A8ED8C35740BA0B706D5856E22D709BE1E001CF8C


Signature: 3044022053BC67D7C8C95F5AD9CC0AB59A4B40C3C4868CECE92A972288C3E719DA4F9EE102204F83F61F2EF5C4039B669969F181797743B56531231F9C91C7470EDBC6E87B94


Private Key ->  : 30818D020100301006072A8648CE3D020106052B8104000A04763074020101042083EF3EC6368C719456FA126B6E4541205CF14199AC9CED08D04CD6DE05509A57A00706052B8104000AA14403420004E5518C2D0FA9AF8C6FEBF3B0142AFDBCA26F4AE08ACA9A82199CBC4292B5697E6DAFB1C949BEFF8E943B95EB7DE5A49DC65DE374B1707C675D15E8929207B3FE
Public Key ->  :  3056301006072A8648CE3D020106052B8104000A03420004E5518C2D0FA9AF8C6FEBF3B0142AFDBCA26F4AE08ACA9A82199CBC4292B5697E6DAFB1C949BEFF8E943B95EB7DE5A49DC65DE374B1707C675D15E8929207B3FE
```

Elliptic js verification

```const EC = require('elliptic').ec

var ec = new EC('secp256k1');

const keyPair = ec.keyFromPublic({
    x: "e5518c2d0fa9af8c6febf3b0142afdbca26f4ae08aca9a82199cbc4292b5697e".toString('hex'),
    y: "6dafb1c949beff8e943b95eb7de5a49dc65de374b1707c675d15e8929207b3fe".toString('hex')
});



const msgHash = "C8ED5E65713F8170B8D0769A8ED8C35740BA0B706D5856E22D709BE1E001CF8C";

const signature = "3044022053BC67D7C8C95F5AD9CC0AB59A4B40C3C4868CECE92A972288C3E719DA4F9EE102204F83F61F2EF5C4039B669969F181797743B56531231F9C91C7470EDBC6E87B94"




console.log(keyPair.verify(msgHash, signature))
```
Output 
```false```

**Comment by dcousens** [comment]
@eddywm why don't you post your failling signature examples?

**Comment by eddywm** [comment]
Java signing code.

`import org.bouncycastle.jce.provider.BouncyCastleProvider;

import javax.xml.bind.DatatypeConverter;
import java.io.UnsupportedEncodingException;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.security.spec.ECGenParameterSpec;

/**
 * Created by eddylloyd on  11/14/17.
 * Tuesday  9:38 AM
 */
public class A {



    public static void main(String[] args) throws NoSuchAlgorithmException, InvalidAlgorithmParameterException, InvalidKeyException, UnsupportedEncodingException, NoSuchProviderException, SignatureException {

        Security.addProvider(new BouncyCastleProvider());

        MessageDigest sha256Digest = MessageDigest.getInstance("SHA-256");

        KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance("ECDSA", "BC");

        ECGenParameterSpec ecGenParameterSpec = new ECGenParameterSpec("secp256k1");

        SecureRandom random = SecureRandom.getInstance("SHA1PRNG");

        keyPairGenerator.initialize(ecGenParameterSpec, random);

        KeyPair keyPair = keyPairGenerator.genKeyPair();

        PrivateKey privateKey = keyPair.getPrivate();

        PublicKey publicKey = keyPair.getPublic();



        System.out.println("Public Key: "+ publicKey  + "\n\n");


        Signature signature = Signature.getInstance("ECDSA", "BC");
        signature.initSign(privateKey, new SecureRandom());

        byte[] hashedMessage = sha256Digest.digest("This is the message".getBytes(StandardCharsets.UTF_8));


        signature.update(hashedMessage);

        byte[] signatureBytes = signature.sign();


        System.out.println("Original Message in hex: "+ Conversions.byteArrayToFlatArray("This is the message".getBytes(StandardCharsets.UTF_8)));

        System.out.println("SHA256 Hashed Message in Hex: "+ Conversions.byteArrayToHexString(hashedMessage)  + "\n\n");


        System.out.println("Signature: "+ DatatypeConverter.printHexBinary(signatureBytes) + "\n\n");



        System.out.println("Private Key -> Format : " +  DatatypeConverter.printHexBinary(privateKey.getEncoded()));
        System.out.println("Public Key -> Format :  " +DatatypeConverter.printHexBinary(publicKey.getEncoded()));



    }
}
`

Output

`Public Key: EC Public Key [1f:aa:2f:fe:55:f5:a6:a5:da:a9:ac:cb:7e:0f:23:25:07:db:6e:70]
            X: e5518c2d0fa9af8c6febf3b0142afdbca26f4ae08aca9a82199cbc4292b5697e
            Y: 6dafb1c949beff8e943b95eb7de5a49dc65de374b1707c675d15e8929207b3fe



Original Message in hex: 5468697320697320746865206D657373616765
SHA256 Hashed Message in Hex: C8ED5E65713F8170B8D0769A8ED8C35740BA0B706D5856E22D709BE1E001CF8C


Signature: 3044022053BC67D7C8C95F5AD9CC0AB59A4B40C3C4868CECE92A972288C3E719DA4F9EE102204F83F61F2EF5C4039B669969F181797743B56531231F9C91C7470EDBC6E87B94


Private Key -> Format : 30818D020100301006072A8648CE3D020106052B8104000A04763074020101042083EF3EC6368C719456FA126B6E4541205CF14199AC9CED08D04CD6DE05509A57A00706052B8104000AA14403420004E5518C2D0FA9AF8C6FEBF3B0142AFDBCA26F4AE08ACA9A82199CBC4292B5697E6DAFB1C949BEFF8E943B95EB7DE5A49DC65DE374B1707C675D15E8929207B3FE
Public Key -> Format :  3056301006072A8648CE3D020106052B8104000A03420004E5518C2D0FA9AF8C6FEBF3B0142AFDBCA26F4AE08ACA9A82199CBC4292B5697E6DAFB1C949BEFF8E943B95EB7DE5A49DC65DE374B1707C675D15E8929207B3FE
`

Elliptic js verification

`const EC = require('elliptic').ec

var ec = new EC('secp256k1');

const keyPair = ec.keyFromPublic({
    x: "e5518c2d0fa9af8c6febf3b0142afdbca26f4ae08aca9a82199cbc4292b5697e".toString('hex'),
    y: "6dafb1c949beff8e943b95eb7de5a49dc65de374b1707c675d15e8929207b3fe".toString('hex')
});



const msgHash = "C8ED5E65713F8170B8D0769A8ED8C35740BA0B706D5856E22D709BE1E001CF8C";

const signature = "3044022053BC67D7C8C95F5AD9CC0AB59A4B40C3C4868CECE92A972288C3E719DA4F9EE102204F83F61F2EF5C4039B669969F181797743B56531231F9C91C7470EDBC6E87B94"




console.log(keyPair.verify(msgHash, signature))
`
Output 
`false`

**Comment by eddywm** [comment]
@dcousens it is now added !

**Comment by indutny** [comment]
From a quick look it appears that you're passing the signature in DER encoded format which is not supported natively by elliptic. We should probably parse it at some point, but it could as well be parsed by: https://www.npmjs.com/package/asn1.js

**Comment by dcousens** [comment]
@eddywm if you want,  https://www.npmjs.com/package/bip66 will decode to `r` and `s` `Buffers` which you could use with `elliptic`

**Comment by eddywm** [comment]
@indutny  @dcousens . Even after adding a DER decoder, it is still failing.

``` 
let signature = new Buffer("30450221009dfb3ee69cc4535bb7c450f0ea2e874fc45b26911a5d752b25865e962dcb875a0220110da89c711e31eca87680aaef97997cbb9d0937389b092c971386a9b95595ad", "hex")

var bip66 = require('bip66')

signature = bip66.decode(signature)
```

```
{ r: <Buffer 00 9d fb 3e e6 9c c4 53 5b b7 c4 50 f0 ea 2e 87 4f c4 5b 26 91 1a 5d 75 2b 25 86 5e 96 2d cb 87 5a>,
  s: <Buffer 11 0d a8 9c 71 1e 31 ec a8 76 80 aa ef 97 99 7c bb 9d 09 37 38 9b 09 2c 97 13 86 a9 b9 55 95 ad> }
false
```

**Comment by eddywm** [comment]
The problem is now fixed ! The exported format of the  public key was not coherent with what Elliptic Nodejs was expecting.

**Comment by sinnlosername** [comment]
Could you explain what was wrong with the key?  @eddywm

**Comment by dantonyblanco** [comment]
@eddywm What was the format that ended up working?
