### ISSUE TITLE
Expose functions to convert point to JSON and back

### ISSUE THREAD

**Issue by lucyq** [indutny/elliptic#155]
We are using this library for building an oblivious pseudo-random function. 
We currently need a mechanism for passing a point between a client's browser and the server. 
It is unclear how we can construct a point object based on a string representation. 
Note: we are using ed25519

Thanks!

**Comment by indutny** [comment]
Hello @lucyq !

Sorry for lack of documentation in that area.

The best way to do it would probably be through `EDDSA` class, that has following methods:

* `encodePoint`
* `decodePoint`

Both return arrays of integers that can be passed to/from browsers.

Hope this helps!

**Comment by lucyq** [comment]
Thanks!
