### ISSUE TITLE
How to use without nodejs

### ISSUE THREAD

**Issue by serkandaglioglu** [indutny/elliptic#156]
Is that possible use this library in html file without nodejs?

**Comment by indutny** [comment]
Yes, one of these files should work: https://github.com/indutny/elliptic/tree/master/dist

**Comment by indutny** [comment]
Thank you for opening the issue here.

Would you care to provide any information at all? I'll be glad to help you as soon as I'll know anything at all.

**Comment by serkandaglioglu** [comment]
I loaded js file and just create EC instance but it throws error below :
The error : Uncaught ReferenceError: EC is not defined

```
<!DOCTYPE html>
<html>
<head>
	<title>EC Test</title>

	<script type="text/javascript" src="ec.js"></script>
	<script type="text/javascript">
		var ec = new EC('secp256k1');
	</script>
</head>
<body></body>
</html>
```

**Comment by indutny** [comment]
Ah, I see. Could you try `elliptic.EC`, please?

**Comment by serkandaglioglu** [comment]
Unfortunately still same error

**Comment by serkandaglioglu** [comment]
lowecase 'ec' worked
`var ec = new elliptic.ec('secp256k1')`

**Comment by indutny** [comment]
Great!
