### ISSUE TITLE
Signatures incorrect length when signing data with some key pairs

### ISSUE THREAD

**Issue by blmalone** [indutny/elliptic#158]
The code below runs a signing operation on the sha256 hash of `Test message`, each time creating a new key pair to perform the signature.

It seems that we intermittently get returned incorrect lengths for the generated `r` and `s` values, where length would = 63 instead of 64 hex characters.

If a zero is prepended to the shortened value, then the resulting signature verifies successfully.

```
import { ec as EC } from "elliptic"; 
const ec = new EC("p256");
import * as Hash from "hash.js";

let key;
let pub;

for(var i = 0; i < 100; i++) {
    key = ec.genKeyPair();
    pub = key.getPublic();
    
    const hash = Hash["sha256"]().update("Test message").digest("hex");
    const sig = key.sign(hash);
    
    if(sig.r.toString("hex").length == 63) {
        console.log(sig.r.toString("hex"), "r is of len 63: loop >", i)
    }
    if(sig.s.toString("hex").length == 63) {
        console.log(sig.s.toString("hex"), "s is of len 63: loop >", i)
    }
}

```

**Comment by fanatid** [comment]
https://github.com/indutny/bn.js/blob/98ac84e81dc02d178168460e5889c80840853a44/lib/bn.js#L440

`sig.r.toString('hex', 64)`

**Comment by blmalone** [comment]
@fanatid awesome, thank you!
