### ISSUE TITLE
Shortened r, s values from ECDSA signature?

### ISSUE THREAD

**Issue by alex-miller-0** [indutny/elliptic#163]
I recently ran into a situation where the `s` value (when transformed to a hex string) was 63 characters (instead of 64).

Unfortunately, I lost the entropy and can't reproduce the situation.

I'm not sure if this is actually a bug but wanted to bring it to your attention. If it's not a bug, is the intention to leave off a trailing zero, which will get filled in when converted to a bytes buffer? 

I need to send signatures in `rsv` hex string format and for now, my hot fix for this apparent edge case is to add a `0` to the end of each component that is 63 characters. Is this safe?

**Comment by fanatid** [comment]
@alex-miller-0 how you export values to hex string? if you use `.toString` method from `bn.js` better pass `padding` as 64
https://github.com/indutny/bn.js/blob/e69c617b3297b99aca429f30842e27979ef9beb5/lib/bn.js#L447

**Comment by alex-miller-0** [comment]
Thanks! I was not aware of that API. I'll close this issue since it seems unlikely it is even related to `elliptic`.

**Comment by woodyjon** [comment]
Waouww, thanks a lot for that issue. I could not understand my issue. The `padding` did the trick!
