### ISSUE TITLE
calling .mul on infinity point

### ISSUE THREAD

**Issue by benediamond** [indutny/elliptic#189]
multiplying the _infinity_ point by a scalar fails.

```javascript
const BN = require('bn.js')
const EC = require('elliptic')

var curve = new EC.ec('secp256k1'); // e.g.---same problem for other curves

curve.g.mul(0).mul(new BN(1234))
```

returns

```javascript
Thrown:
TypeError: Cannot read property 'redMul' of null
    at Point._getBeta (/Users/benediamond/node_modules/elliptic/lib/elliptic/curve/short.js:291:38)
    at ShortCurve._endoWnafMulAdd (/Users/benediamond/node_modules/elliptic/lib/elliptic/curve/short.js:226:18)
    at Point.mul (/Users/benediamond/node_modules/elliptic/lib/elliptic/curve/short.js:429:23)
```

elliptic version is 6.5.0, node version is v12.1.0.

**Comment by benediamond** [comment]
@stuarth1

**Comment by benediamond** [comment]
@fanatid could possibly be solved by adding
```javascript
  if (this.isInfinity())
    return this;
```
on line 424: https://github.com/indutny/elliptic/blob/ee7970b92f388e981d694be0436c4c8036b5d36c/lib/elliptic/curve/short.js#L422-L431

but not sure about the architecture of the codebase---thoughts?

**Comment by fanatid** [comment]
Yeah, i think you are correct. `Point#mul` should have at beginning:
```js
   if (this.isInfinity())
     return this;
```

**Comment by benediamond** [comment]
@fanatid should I raise the PR?

**Comment by fanatid** [comment]
PR's are always welcome, but I think only Fedor can press merge button :)

**Comment by benediamond** [comment]
should we ping him...? @indutny

if this looks good, I'm happy to draft the PR! thanks.

**Comment by indutny** [comment]
:+1: from me
