### ISSUE TITLE
EC Canonical Signature fails in specific cases

### ISSUE THREAD

**Issue by viswanathkgp12** [indutny/elliptic#195]
EC Canonical Signature fails in specific cases. In the example code below, a failure case is demonstrated, where a signature for messageHash is generated using elliptic and verified.

Elliptic signature verification returns true, but the same when verified through secp256k1 fails. Also it is observed that elliptic generated signature in this particular case has incorrect length. i.e., r, s are not of 32 bytes in length. Still the elliptic package verification results true.

The issue may not occur when a different messageHash is used, say e55ef2ea7deb1e128725ebd2e030619143b52466ba118735c7746faf4d2ee319

```
const secp256k1 = require('secp256k1/elliptic');
const elliptic = require("elliptic");
const ec = new elliptic.ec('secp256k1');

// Failure case
const msgHash = "5f1775cf305dbd4c46d93110919341556727ea8fbc30708f430184864578be47";
const privateKeyStr = "6639c03b8899cfb29ada1adf90844cf09d5a59042b025cfc19c1edb9452fdfdc";
const publicKeyStr = "0313af1df7ffc1f20b408a2b6d3cbf7bf0d2eebd019062919d995f18d62670a70c";

// Elliptic Signing
let sigObj = ec.sign(msgHash, privateKeyStr, { canonical: true });

signature = {
    r: sigObj.r.toString('hex'),
    s: sigObj.s.toString('hex')
};
console.log("r: ", signature.r, "s: ", signature.s);

const pubKey = ec.keyFromPublic(publicKeyStr, 'hex');
// Elliptic Verification
const ellipticVerified = ec.verify(msgHash, signature, pubKey);

console.log("Elliptic Sig Verifed: ", ellipticVerified);

const rBuf = Buffer.from(signature.r, "hex");
const sBuf = Buffer.from(signature.s, "hex");
const sigBuf = Buffer.concat([rBuf, sBuf]);
const msgHashBuf = Buffer.from(msgHash, "hex");
const pubKeyBuf = Buffer.from(publicKeyStr, "hex");

// SECP256k1 Verification
const secp256k1Verified = secp256k1.verify(msgHashBuf, sigBuf, pubKeyBuf);
console.log("SECP256K1 Verified: ", secp256k1Verified);

```

**Comment by fanatid** [comment]
`sigObj.s.toString('hex')` transforming to 63 symbols strings, you need `sigObj.s.toString('hex', 64)` -- now strings will contain 64 symbols and buffers from r/s in hex will contain 32 bytes

`toArrayLike` example in [cryptocoinjs/secp256k1-node](https://github.com/cryptocoinjs/secp256k1-node): https://github.com/cryptocoinjs/secp256k1-node/blob/v3.7.1/lib/elliptic/index.js#L212-L213

**Comment by vishvaultbank** [comment]
True but signature verification still fails if verified through secp256k1. Also for the above case, r and s values are always the same no matter how many times the sign operation is carried out.

**Comment by fanatid** [comment]
I just changed `.toString('hex')` to `.toString('hex', 64)` and run script:
```bash
r:  08cb7047482766ee777c0f62ca07701a32168b50a145ab1d0b7c28c797c6b6ef s:  080b6ed20093098c4d407913e18f2f75d945704d89293082926ef94676f5ccae
Elliptic Sig Verifed:  true
SECP256K1 Verified:  true
```
Looks OK, right?

**Comment by viswanathkgp12** [comment]
Yes. Thanks.

**Comment by fanatid** [comment]
If issue resolved, please close it.
