### ISSUE TITLE
Missing leading zero when exporting as BN object

### ISSUE THREAD

**Issue by hfossli** [indutny/elliptic#207]
When running this code
```
const key1 = ec.genKeyPair();
console.log(key1);
console.log(key1.getPrivate("hex"));
console.log(key1.getPrivate().toString("hex"));
```

I get
```
<Key priv: 0f6fa353aea3d2a992eff69423b8479279b90fd00675e657b8d5d1cbf92709f0 pub: null > 
0f6fa353aea3d2a992eff69423b8479279b90fd00675e657b8d5d1cbf92709f0
f6fa353aea3d2a992eff69423b8479279b90fd00675e657b8d5d1cbf92709f0 
```

But I expected
```
<Key priv: 0f6fa353aea3d2a992eff69423b8479279b90fd00675e657b8d5d1cbf92709f0 pub: null > 
0f6fa353aea3d2a992eff69423b8479279b90fd00675e657b8d5d1cbf92709f0
0f6fa353aea3d2a992eff69423b8479279b90fd00675e657b8d5d1cbf92709f0 
```
(notice the leading zero is missing when exporting the key as `.getPrivate().toString("hex")` instead of `.getPrivate("hex")`)

Is this a bug or is it by design?

**Comment by fanatid** [comment]
This happened because you need call `toString` as `toString('hex', 2)` for padding. If you check `getPrivate` code, you can see that `getPrivate('hex')` equal to `getPrivate().toString(16, 2)`.
https://github.com/indutny/elliptic/blob/60489415e545efdfd3010ae74b9726facbf08ca8/lib/elliptic/ec/key.js#L69-L74

**Comment by hfossli** [comment]
Aweeesome!🥰

**Comment by hfossli** [comment]
🤔 what if.... what if the key randomly has 2 leading zeros, wouldn't it then be better to say toString(16, 32)?

**Comment by fanatid** [comment]
Yes, right call will be `toString(16, 32)`. Sorry for first wrong example.

**Comment by hfossli** [comment]
Thanks. I don't know. I know from secp256r1 that leading zeros is important if the first hex value is >= 80
