### ISSUE TITLE
another newbie question

### ISSUE THREAD

**Issue by mrose17** [indutny/elliptic#23]
i am transitioning some code from https://github.com/thejh/node-curve25519 to this package. as mentioned in an earlier issue, this is the curve25519-donna algorithm, which is described here: http://cr.yp.to/ecdh.html

what i am seeing is that the same inputs for the local private key and the remote public are producing different values. this leads me to believe that i am using the API in this package incorrectly (since i know that the other package produces good values with this input, and I'm confident that this package will produce good values if invoked correctly).

```
% node donna.js
               my private key =843b75caa5bdb940f740b7d9262e2ae9937c946dca7b0d18617ff5a1a33f46

    old pkg says my public key=200b85ac0e08d3fd0a0be90436765119037d30b7bff56f07cfab51ec1691837f
    new pkg says my public key=098aac55eae1f4c026fe443614ef450e9d7a4d2ac740ad67c9ff84ff41aab70f

  old pkg says your public key=97b22cf64c25ae2db61d07618ff291086feff2ae8779e57be59e988c33916b0f
  new pkg says your public key=17b22cf64c25ae2db61d07618ff291086feff2ae8779e57be59e988c33916b22

old pkg says the shared secret=91bae78939e897c5996417c77c5e3e19f82f4143acb34ef23848d3b6cc1f9930
new pkg says the shared secret=2a8fef7deb2436b8877fc8302e05eb9884099bc289fc8419de9f43c450c7c603
```

the source file is here https://gist.github.com/mrose17/36a9f5ada76bfab4b8bc

could you "clue me up" as to what i'm doing wrong here? many thanks!

**Comment by indutny** [comment]
@mrose17 Looking into it...

I could tell for sure that `your public key` thing is the same up to the curve modulus. For some reason `curve25519` package does not `mod` it before returning to you.

Also `curve25519` C module seems to amend the public key before using it, but it seems that even when uncommenting section in your example - it still differs.

**Comment by indutny** [comment]
I wonder if it could be that Adam is using http://elligator.cr.yp.to/poster.pdf in his donna code.

**Comment by indutny** [comment]
Ok, figured it out :) It does everything in reverse!

```javascript
var elliptic   = require('./lib/elliptic.js')
  , ec         = new elliptic.ec('curve25519')
  , mysecret   = new Buffer('00843b75caa5bdb940f740b7d9262e2ae9937c946dca7b0d18617ff5a1a33f46', 'hex')
  , rev = new Buffer(32);


 mysecret[0] &= 248
 mysecret[31] &= 127
 mysecret[31] |= 64
for (var i = 0; i < 32; i++)
  rev[i] = mysecret[32 - i - 1];
 
var mykey      = ec.keyFromPrivate(rev)
  , yourpublic = new Buffer('97b22cf64c25ae2db61d07618ff291086feff2ae8779e57be59e988c33916b0f', 'hex')
  , yourkey    = ec.keyFromPublic(yourpublic)
  , shared     = mykey.derive(yourkey.getPublic())
 
console.log('               my private key ='+mykey.getPrivate('hex') + '\n')
 
console.log('    old pkg says my public key='+'200b85ac0e08d3fd0a0be90436765119037d30b7bff56f07cfab51ec1691837f')
// !!!!!!!!
// This one is reversed!
// !!!!!!!!
console.log('    new pkg says my public key='+mykey.getPublic('hex') + '\n')
 
console.log('  old pkg says your public key='+yourpublic.toString('hex'))
console.log('  new pkg says your public key='+yourkey.getPublic('hex') + '\n')
 
console.log('old pkg says the shared secret='+'91bae78939e897c5996417c77c5e3e19f82f4143acb34ef23848d3b6cc1f9930')
console.log('new pkg says the shared secret='+shared.toString(16))
```

**Comment by indutny** [comment]
Thanks for sharing, though!

**Comment by mrose17** [comment]
thanks for looking into this. very odd. i was expecting something less esoteric. ok, so basically, the trick is to know when the flip the results for transmission to the other side (my public key) or use (derived shared secret). i've updated the gist above to reflect that.

    https://gist.github.com/mrose17/36a9f5ada76bfab4b8bc

sorry for the confusion!

**Comment by indutny** [comment]
```
/Users/indutny/Code/indutny/elliptic/2.js:26
curve25519.makeSecretKey(C_mysecret)
           ^
TypeError: Object #<Object> has no method 'makeSecretKey'
    at Object.<anonymous> (/Users/indutny/Code/indutny/elliptic/2.js:26:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by mrose17** [comment]
hmmm... just to confirm, we're talking about this package

    https://github.com/thejh/node-curve25519

(or at least that's the one i'm talking about!)

**Comment by indutny** [comment]
Yeah, it is just your gist that does not work :) May be you are using older version?

**Comment by mrose17** [comment]
sorry about that. here's what i did:

1. (temporarily) add this dependency to package.json for elliptic:

            "curve25519": "git://github.com/thejh/node-curve25519.git"

2. the usual `npm -l install`

3. ran this gist: https://gist.github.com/mrose17/36a9f5ada76bfab4b8bc

maybe there is a version mismatch, but i'm not sure how i did that...
