### ISSUE TITLE
Array.fill() not working in Chrome 38.

### ISSUE THREAD

**Issue by ajelden** [indutny/elliptic#237]
Hello. We have been using v6.4.1 for a couple of years, the oldest browser we need to support is Chrome 38. I updated to 6.5.3 yesterday, and I am seeing that it is not working in Chrome 38. I tracked down a point of failure here:
https://github.com/indutny/elliptic/blob/master/lib/elliptic/utils.js#L17 , where Array.fill() is used.

Would it be possible to replace that call with something compatible with Chrome 38?

Thank you.

**Comment by indutny** [comment]
I'm sorry to hear that!

The Chrome version number is a bit confusing for me. 38 was released in 2015. Is this the one you are referring too?

**Comment by ajelden** [comment]
Sorry. I should have said Chromium 38. From https://en.wikipedia.org/wiki/Chromium_(web_browser)#2014 :
"Chromium 38.0 was released on 22 June 2014, with the initial release version 38.0.2063.0.[29] This development cycle resulted in the release of Chrome 38.0.2125.101 on 7 October 2014."

Yes, it's old, but our software has to run on an LG 2017 SmartTV which uses Chromium 38 as its web engine.

**Comment by indutny** [comment]
Is there a chance you could just add a polyfill for this?

**Comment by ajelden** [comment]
I'll try that.

**Comment by ajelden** [comment]
`core-js/features/array/fill` polyfill is working--thanks.

**Comment by indutny** [comment]
Yay, glad to hear this!
