### ISSUE TITLE
Check for empty message

### ISSUE THREAD

**Issue by Kagami** [indutny/elliptic#25]
Should the `sign` function check `msg` for empty string/array somewhere in [this](https://github.com/indutny/elliptic/blob/master/lib/elliptic/ec/index.js#L102) place?
Signature of empty message (`z = 0`) could be trivially forged per [[1]](https://crypto.stackexchange.com/a/9383), [[2]](https://github.com/bitcoin/secp256k1/issues/43#issuecomment-47997596).

**Comment by indutny** [comment]
If you are passing not a hash of some input data - elliptic assumes that you know what you are doing :)

The suggested use is to put a sha256 as an input of secp256k1 sign method.
