### ISSUE TITLE
Strange import error

### ISSUE THREAD

**Issue by ivan-kleshnin** [indutny/elliptic#30]
I'm getting "Cannot read property version of undefined" on the first line of this block:
```
elliptic.version = require('../package.json').version; // required var is undefined
elliptic.utils = require('./elliptic/utils'); // required var is correct
elliptic.rand = require('brorand'); // required var is correct
```
on browserify bundle. If I comment this line, everything works ok (including other elliptic imports!). 
Can you shed the light on what may cause this error?
Should I post this issue to browserify?

**Comment by indutny** [comment]
What browserify version are you using and what node.js/io.js version?

**Comment by dcousens** [comment]
This is a browserify/watchify version mismatch problem from my own experience.

**Comment by steffenmllr** [comment]
Having the same issue with: `browserify ^8.1.3` and `watchify ^2.3.0`

**Comment by ivan-kleshnin** [comment]
@indutny I had this issue with many browserify / watchify and node version combinations.
Strange thing that only elliptic seems to suffer from this bug.

**Comment by indutny** [comment]
@ivan-kleshnin I got you. It is quite odd to see this, since I'm building the `dist/` folder contents with `browserify` (https://github.com/indutny/elliptic/blob/master/Makefile).

I'll look into it over weekend or at Monday.

**Comment by linxtion** [comment]
Same issue here with elliptic.

**Comment by indutny** [comment]
Is there any way to reproduce it?

**Comment by chevdor** [comment]
same issue here

**Comment by dcousens** [comment]
It can be reproduced with "browserify": "^8.1.1" and "watchify": "^2.2.1".

Latest of either resolves this issue.

This is not elliptic's fault AFAIK.

**Comment by indutny** [comment]
@dcousens: so is it fixed in browserify now?

**Comment by dcousens** [comment]
It's a combination thing only.  If you just restart watchify it resolves
the issue too.

**Comment by dcousens** [comment]
And yes,  it is fixed if you use browserify 9.0.0 and watchify 3? (Latest,
whatever that is)

**Comment by indutny** [comment]
Cool! Thank you @dcousens . Could you guys please verify this and let me know if it is resolved for you as well?

**Comment by ivan-kleshnin** [comment]
@indutny, @dcousens, thanks! 
I confirm that with latest browserify / watchify issue is no longer valid.

**Comment by indutny** [comment]
Cool, closing! Thank you everyone.

**Comment by chevdor** [comment]
Same as @ivan-kleshnin 
First I had an ancient browserify in my package.json but also karma-browserify was pointing to 8.0.2
Using the latest version of browserify fixed the issue.
