### ISSUE TITLE
Dependabot alerts being raised for elliptic

### ISSUE THREAD

**Issue by justinclift** [indutny/elliptic#319]
GitHub's Dependabot has today started creating alerts in repositories using elliptic.

@indutny is this stuff (below) already on people's radar for looking into? :smile:

## Elliptic allows BER-encoded signatures

In the Elliptic package 6.5.6 for Node.js, ECDSA signature malleability occurs because BER-encoded signatures are allowed.

Affected versions: >= 5.2.1, <= 6.5.6

Fixed versions: None

## Elliptic's ECDSA missing check for whether leading bit of r and s is zero

In the Elliptic package 6.5.6 for Node.js, ECDSA signature malleability occurs because there is a missing check for whether the leading bit of r and s is zero.

Affected versions: >= 2.0.0, <= 6.5.6

Fixed versions: None

## Elliptic's EDDSA missing signature length check

In the Elliptic package 6.5.6 for Node.js, EDDSA signature malleability occurs because there is a missing signature length check, and thus zero-valued bytes can be removed or appended.

Affected versions: >= 4.0.0, <= 6.5.6

Fixed versions: None

**Comment by justinclift** [comment]
This seems to be the source of the Dependabot alerts: https://github.com/indutny/elliptic/pull/317

**Comment by mfernandes-alcumus** [comment]
Mend is flaggin this as vulnerability can this be resolved please. its causing us a lot of concerns

**Comment by vanthorng** [comment]
Is there any way that we can fix this issue, as it is showing no patch available.

**Comment by justinclift** [comment]
Looks like a new `6.5.7` release has been tagged, which includes the PR that solves the Dependabot issues: https://github.com/indutny/elliptic/releases/tag/v6.5.7

**Comment by justinclift** [comment]
Thanks for getting the PR merged and the new release sorted out @indutny. :smile:

**Comment by indutny** [comment]
Happy to help, sorry for not doing it on time!

**Comment by justinclift** [comment]
No worries, they're only `Low` severity Dependabot warnings.  It's all good. :smile:

**Comment by justinclift** [comment]
Closing this issue, as the new release does indeed fix the Dependabot warnings.  Confirmed it in one of my project repos.
