### ISSUE TITLE
make the library smaller, or break it up

### ISSUE THREAD

**Issue by fruiz500** [indutny/elliptic#32]
I'd really like to use the library to implement the Edwards e521 curve on my own PassLok app (also on GitHub), which is currently using SJCL. People are suspicious about the NIST curves, which are what SJCL supports. Now, what's holding me from using elliptic.js is its sheer size. 180 kiloBytes!

Maybe you can break it up into smaller chunks, so I only need to add the components that really get used?

Thanks!

**Comment by indutny** [comment]
@fruiz500 I think you could drop it to 145kb (for un-minimized) and to 79kb (minimized) by removing the pre-computed values for secp256k1 curve. Let me see if it could be improved even further...

**Comment by indutny** [comment]
But important thing is that it actually compresses down to 39kb with gzip, so it should not be a big deal after all.

Without precomputed secp256k1 it is just 20kb after gzip. Do you want me to distribute it too?

**Comment by indutny** [comment]
Anyway, published https://github.com/indutny/elliptic/blob/master/dist/elliptic-small.min.js 79kb minified code for you! :)

**Comment by fruiz500** [comment]
Thanks Fedor, but minimized code won't do. In order to make my own code as free from tampering at the source as possible, I am adding all the libraries used into a single html file, and then I publish the md5, sha1 and sha256 of the result, plus a video of myself reading the sha256.

If I add a minimized portion to the code, those auditing it will complain that it is un-auditable. They have complained about other parts in the past, forcing me to add libraries with full comments, etc.

The only functions I am going to need are those related to Diffie-Hellman and digital signatures. maybe there is a way to get those separated out of the rest?

**Comment by indutny** [comment]
@fruiz500 there is not much except it :) Anyway gzip'ed dist/elliptic-small.js is very small (35kb). I assume that you can gzip your distribution and read out load sha256 has of it without sacrificing the code readability :)
