### ISSUE TITLE
elliptic.version broken with browserify

### ISSUE THREAD

**Issue by RichardLitt** [indutny/elliptic#35]
The line `elliptic.version = require('../package.json').version;` throws an error with `require('../package.json')` coming up as undefined for me, and I'm not sure why. I was able to manually change the line to `elliptic.version = '1.0.1';`, and everything worked fine again. This only seemed to be a problem when using watchify. 

Not sure what else would be useful for this bug report - I'm using node v0.12, browserify, transforms `reactify` and `brfs` with `{globals: true}` for brfs.

**Comment by indutny** [comment]
Please update your browserify version, this was happening on old version of it and doesn't happen now anymore.

**Comment by RichardLitt** [comment]
Thanks! worked.

**Comment by indutny** [comment]
Yay!
