### ISSUE TITLE
recover key from signature method

### ISSUE THREAD

**Issue by wanderer** [indutny/elliptic#36]
You can recover the public key given a recover bit from a signature. It is implemented here https://github.com/cryptocoinjs/ecdsa/blob/master/lib/ecdsa.js#L114-L152

**Comment by indutny** [comment]
Nice! Do you feel like you might be interested in contributing this?

**Comment by wanderer** [comment]
@indutny if you don't mind me being slow and bugging you. :P

**Comment by wanderer** [comment]
from section 4.1.6 [Public Key Recovery Operation](http://www.secg.org/sec1-v2.pdf)

1. Let x = r + jn.
2. Convert the integer x to an octet string X of length mlen using the conversion routine
specified in Section 2.3.7, where mlen = d(log2 p)/8e or mlen = dm/8e.
3. Convert the octet string 0216kX to an elliptic curve point R using the conversion routine
specified in Section 2.3.4. If this conversion routine outputs “invalid”, then do another
iteration of Step 1.
4. If nR 6= O, then do another iteration of Step 1.
5. Compute e from M using Steps 2 and 3 of ECDSA signature verification.
6. For k from 1 to 2 do the following.
  1. Compute a candidate public key as:
      `Q = r−1(sR − eG).`
  2. Verify that Q is the authentic public key. (For example, verify the signature of a
certification authority in a certificate which has been truncated by the omission of
Q from the certificate.) If Q is authenticated, stop and output Q.
  3. Change R to −R.

**Comment by wanderer** [comment]
WIP RP #34

**Comment by wanderer** [comment]
landed in 3.1.0!
