### ISSUE TITLE
How is it compared with TweetNaCl.js?

### ISSUE THREAD

**Issue by b1rdex** [indutny/elliptic#41]
https://github.com/dchest/tweetnacl-js

**Comment by indutny** [comment]
idk :) You tell me!

**Comment by sublimator** [comment]
I don't have any hard numbers on hand to back me up but I think it's faster :) and of course it implements secp256k1 as well as ed25519.  Currently it doesn't really support the latter in an immediately useful form, but there's a WIP pull request #40 for EdDSA which tweetnacl implements that I'm hoping @indutny will help get ready for merging some time soon :) :) :)

**Comment by sublimator** [comment]
EdDSA was merged by the way. I will see if I can make some benchmarks at some point, as I'm curious to see exactly how much faster elliptic is.

**Comment by taoeffect** [comment]
So has anyone done any serious comparison? I'm also curious if there's are any other meaningful differences?
