### ISSUE TITLE
Point encoding 

### ISSUE THREAD

**Issue by sublimator** [indutny/elliptic#42]
```javascript
function compressedPoint(p) {
  const x = p.getX().toArray();
  const y = p.getY();
  while (x.length < 32) x.unshift(0)
  return [y.isEven() ? 0x02 : 0x03].concat(x);
}
```

Currently for implementing some seed -> secret routines (the algorithm is set in stone) which involves hashing byte representations of points, I needed a little utility function. I note the only code for this currently in elliptic is in the EC/KeyPair#getPublic method and not immediately useful.

Maybe some Point.encode(encoding) / curve.decodePoint(encoding) methods? Shrug?

**Comment by indutny** [comment]
I guess this sounds reasonable to me. Feel free to open PR for this.

**Comment by indutny** [comment]
Though, it will need to use byte length of `curve.p` instead of `32`.

**Comment by sublimator** [comment]
Of course :) Was just example from se application cose

**Comment by sublimator** [comment]
Code. Damn mobile :)
