### ISSUE TITLE
RNG is not provably secure?

### ISSUE THREAD

**Issue by shelby3** [indutny/elliptic#5]
Apparently your RNG is not as provably secure as the one in SJCL as you appear to rely on the built in browser RNG, which might be compromised.

https://github.com/indutny/elliptic/blob/master/lib/elliptic/rand.js

Some RNGs in operating systems as well as the RNG instruction in CPUs are throught to be potentially compromised.

Note a copy of this comment also appears at the SJCL issue where I learned of the existence of your project.

https://github.com/bitwiseshiftleft/sjcl/issues/168#issuecomment-47460729

**Comment by indutny** [comment]
I assume this could be closed now.
