### ISSUE TITLE
Add coveralls step to CI ?

### ISSUE THREAD

**Issue by sublimator** [indutny/elliptic#51]
It's pretty easy:

1. Just login with github at coveralls
2. Add indutny/elliptic repo and note the $repo_token
3. Install travis gem
4. $ travis encrypt COVERALLS_REPO_TOKEN=$repo_token -r indutny/elliptic -a 

See: http://docs.travis-ci.com/user/encryption-keys/

**Comment by sublimator** [comment]
Then of course, just add coveralls/instanbul to package.json:

```json
  "devDependencies": {
    "coveralls": "~2.10.0",
    "istanbul": "~0.3.5",
    ...
  },
  "scripts": {
    "test": "istanbul test _mocha",
    "coveralls": "cat ./coverage/lcov.info | coveralls",
    ...
  },
```

And in .travis.yml:

```yaml
script:
- npm test --coverage
- npm run-script coveralls
```

I can make a pull request for this, but obviously can't setup coveralls or the repo token :)

**Comment by indutny** [comment]
Hopefully I did everything right :)

**Comment by sublimator** [comment]
Almost!  :)  See #52
