### ISSUE TITLE
Endormorphism optimization bias

### ISSUE THREAD

**Issue by dcousens** [indutny/elliptic#53]
Was just reading through some posts around the net,  and I found this comment by @gmaxwell [on hackernews](https://news.ycombinator.com/item?id=8739610).
The comment (which is just under a year old):

> (2) Some unusual curves can have an optimization which common implementations might take which results in biased nonces. These curves are not widely used on the Internet. I'm doubtful you've ever heard of them (except Bitcoin's curve, which is a GLV curve, but I'm relatively confident _no one_ is using the endomorphism in signing). They also give advice on avoiding that weakness.

It hints at a bias,  though I'm not 100% on the intricacies (at this time).

Just figured I'd ping you @indutny, the paper is at https://www.irisa.fr/celtique/zapalowicz/papers/asiacrypt2014.pdf

Happy to see this closed if this is a non-issue.

**Comment by indutny** [comment]
@dcousens is it about choosing random k1 and k2 in GLV, instead of decomposing big k into k1 and k2?

**Comment by dcousens** [comment]
That sounds about right.

**Comment by indutny** [comment]
@dcousens elliptic decomposes big k into k1, and k2, thus AFAIK it doesn't have this kind of bias.

**Comment by dcousens** [comment]
@indutny could you link to the relevant code?

And no worries,  I just figured it'd be best to at least ask.

**Comment by indutny** [comment]
Sure: https://github.com/indutny/elliptic/blob/master/lib/elliptic/curve/short.js#L222 , no worries! Thanks for asking.
