### ISSUE TITLE
sign interprets message as hex even when it's not hex

### ISSUE THREAD

**Issue by clark800** [indutny/elliptic#56]
The `toArray` function strips non-hex characters without warning. If a user tries to pass a UTF8 string as the message, they may assume that it is signing the string message and not realize that the message is being interpreted as hex with non-hex characters stripped. It would be more defensive to throw an exception here:

https://github.com/indutny/elliptic/blob/master/lib/elliptic/utils.js#L33
https://github.com/indutny/elliptic/blob/master/lib/elliptic/utils.js#L164

**Comment by indutny** [comment]
I think this makes sense. Could you be interested in submitting the fix for this?

**Comment by fanatid** [comment]
Should note, that this problem not only in elliptic.. [hash.js](https://github.com/indutny/hash.js/blob/b8d200196b7e8a335d1f94c6b14366491822b7bb/lib/hash/utils.js#L22) and maybe other libraries.

**Comment by dcousens** [comment]
Again,  one of the scariest parts of the `elliptic` suite is the non-strict typing for me.

**Comment by dcousens** [comment]
Perhaps close in favour of https://github.com/indutny/elliptic/issues/105

**Comment by indutny** [comment]
Agree.
