### ISSUE TITLE
Problem: Elliptic.js use in client browser

### ISSUE THREAD

**Issue by beastybeast** [indutny/elliptic#6]
Hi Fedor

Have a problem as I like to include your library "elliptic.js" into my hobby project  https://pcrypt.org/dev.

(long reason why I like to do this, but I like to implement some new functionality)

The file elliptic.js has been included in the header

When i try to use the library as taken from your example:

var ec = new EC('secp256k1');

var key1 = ec.genKeyPair();
var key2 = ec.genKeyPair();

var shared1 = key1.derive(key2.getPublic());
var shared2 = key2.derive(key1.getPublic());

console.log('Both shared secrets are BN instances');
console.log(shared1.toString(16));
console.log(shared2.toString(16));

The browser complain with the following message:

Uncaught ReferenceError: EC is not defined

in the first line of the code.

What am I doing wrong? You may have an easy solution before I start to dive into this problem or test a lot of other libraries. And it may also be that this will help others.

Looks like almost all ecc libraries are node.js oriented and not browser friendly.

NB: You can see the problem live here: https://pcrypt.org/dev/ecc.php

Best regards
Benny

**Comment by bronze1man** [comment]
Full work example in browser:
```
(function(){
    var ec = new elliptic.ec('curve25519');

    // Generate keys
    var key1 = ec.genKeyPair();
    var key2 = ec.genKeyPair();

    var shared1 = key1.derive(key2.getPublic());
    var shared2 = key2.derive(key1.getPublic());

    console.log('Both shared secrets are BN instances');
    console.log(shared1.toString(16));
    console.log(shared2.toString(16));
})();
``` 
Put this example in README.md may be better.
