### ISSUE TITLE
short curve, jpoint

### ISSUE THREAD

**Issue by fanatid** [indutny/elliptic#63]
Not sure that I'm right, but I think instead
```js
this.zOne = this.z === this.curve.one;
```
should be
```js
this.zOne = this.z.cmp(this.curve.one) === 0;
```
https://github.com/indutny/elliptic/blob/74d28b4815daa681e7234aa91f2af47f8e492d3f/lib/elliptic/curve/short.js#L497

**Comment by indutny** [comment]
I know it is a bit silly, but I mostly cover https://github.com/indutny/elliptic/blob/74d28b4815daa681e7234aa91f2af47f8e492d3f/lib/elliptic/curve/short.js#L475 here. I wonder if changing it to `cmp` will actually make things slower or faster.

**Comment by indutny** [comment]
A bit slower, it seems. Sorry, but closing!

**Comment by fanatid** [comment]
In this case using [doubling-mdbl-2007-bl](https://github.com/indutny/elliptic/blob/74d28b4815daa681e7234aa91f2af47f8e492d3f/lib/elliptic/curve/short.js#L661) and [doubling-mdbl-2007-bl](https://github.com/indutny/elliptic/blob/74d28b4815daa681e7234aa91f2af47f8e492d3f/lib/elliptic/curve/short.js#L732) doesn't make sense
Also, can you answer please, what the formula you're using in [JPoint.mixedAdd](https://github.com/indutny/elliptic/blob/74d28b4815daa681e7234aa91f2af47f8e492d3f/lib/elliptic/curve/short.js#L567)? [2004 Hankerson/Menezes/Vanstone, page 91 ...](http://hyperelliptic.org/EFD/oldefd/jacobian.html#mADD) ?
Thanks!

**Comment by indutny** [comment]
@fanatid these doubling still apply to point that were just converted from cartesian coordinates.

All formulas are from: https://www.hyperelliptic.org/EFD/

**Comment by fanatid** [comment]
My fault, only now I realized that `===` check that `z` is the **same** object that `curve.one`.
Can't find some forumlas at EFD, don't you improve them by yourself and don't use 3rd sources?

**Comment by indutny** [comment]
Most of them are based on EFD with some minor improvements, I don't really remember if there are any that are not. Sorry!

**Comment by fanatid** [comment]
In any case, many thanks for answer! Hope that I find them :)
