### ISSUE TITLE
custom nonce function

### ISSUE THREAD

**Issue by fanatid** [indutny/elliptic#68]
In https://github.com/cryptocoinjs/secp256k1-node/pull/57 we discussed using elliptic in v3.0.0, but it's required custom nonce function. Any ideas how it's can be implemented here? Wrapper for HmacDRBG? Does it make sense move HmacDRBG to separate module?

Relevant links:
[generating nonce in secp256k1-node v3.0.0](https://github.com/cryptocoinjs/secp256k1-node/blob/2ef419080f33b61fd845e8963c910d7cf0e3fd35/lib/ecdsa.js#L66)
[generating nonce in elliptic](https://github.com/indutny/elliptic/blob/58b2ee15346315d6f8c16313005f9421c2599df3/lib/elliptic/ec/index.js#L118)

**Comment by indutny** [comment]
Submitted https://github.com/indutny/elliptic/pull/69 , please take a look ;)
