### ISSUE TITLE
DER parser failing to parse r and s values

### ISSUE THREAD

**Issue by chjj** [indutny/elliptic#78]
Not sure what to make of this. I was using bcoin to verify the entire blockchain when elliptic threw when verifying [this](https://webbtc.com/tx/a618dc10b8a1f9d9a1469b3bb84fc17da86df2d51c27e2aa16fa130953840735) transaction. I figure this is a nonstandard DER signature that elliptic cannot parse for whatever reason.

``` js
var data = {
  msg: 'de17556d2111ef6a964c9c136054870495b005b3942ad7b62628af00293b9aa8',
  sig: '3045022100a9379b66c22432585cb2f5e1e85736c69cf5fdc9e1033ad583fc27f0b7c561d802202c7b5d9d92ceca742829ffbe28ba6565faa8f94556cb091cbc39d2f11d45946700',
  key: '04650a9a1deb523f636379ec70c29b3e1e832e314dea0f791160f3dba628f4f509360e525318bf7892af9ffe2f585bf7b264aa31792744ec1885ce17f3b1ef50f3'
};

require('elliptic').ec('secp256k1').verify(data.msg, data.sig, data.key, 'hex');
```

Original error:

```
Error: Signature without r or s
    at assert (/home/chjj/work/node_modules/bcoin/node_modules/elliptic/lib/elliptic/utils.js:8:11)
    at new Signature (/home/chjj/work/node_modules/bcoin/node_modules/elliptic/lib/elliptic/ec/signature.js:16:3)
    at EC.verify (/home/chjj/work/node_modules/bcoin/node_modules/elliptic/lib/elliptic/ec/index.js:153:15)
    at Object.checksig (/home/chjj/work/node_modules/bcoin/lib/bcoin/script.js:310:24)
    at Object.execute (/home/chjj/work/node_modules/bcoin/lib/bcoin/script.js:841:22)
    at Object.verify (/home/chjj/work/node_modules/bcoin/lib/bcoin/script.js:217:16)
    at TX.<anonymous> (/home/chjj/work/node_modules/bcoin/lib/bcoin/tx.js:925:25)
    at Array.every (native)
    at TX.verify (/home/chjj/work/node_modules/bcoin/lib/bcoin/tx.js:916:22)
    at /home/chjj/work/node_modules/bcoin/lib/bcoin/chain.js:685:17
```

**Comment by dcousens** [comment]
The DER encoding on that signature is wrong,  its 1 byte longer than it says it is (expected `71`, got `73`).

**Comment by chjj** [comment]
@dcousens, yep, just noticed this. Elliptic looks like it does strict length checking on the elements in the signatures. I wrote a function to attempt to shorten overly long DER signatures before passing them into elliptic (in case anyone else runs into this): https://gist.github.com/chjj/1d26c818f2e20afcc33d

Closing now.

**Comment by indutny** [comment]
@chjj this is very important to reject such signatures. If you allow multiplicity in signature encoding - there are potential attacks on hash collisions. I really advise you against using it for new signatures, it can be used to verify old ones (up to some minimal point in the past).

**Comment by chjj** [comment]
@indutny, eventually the bitcoin DERSIG flag will be activated by bcoin once the blocks reach a certain version threshold, requiring signatures to follow the standard encoding, so this shouldn't be an issue. All transactions in accepted to the mempool already get checked for strict DER encoding before being added.

**Comment by indutny** [comment]
@chjj Fantastic! I just wanted to be sure that there is no security risk for you guys!

**Comment by chjj** [comment]
@indutny, thank you. :)

I added an extra note in the comments and a failsafe to make sure this is never done for non-historical data.
