### ISSUE TITLE
Internet Explorer is failing "Object doesn't support property or method 'privBytes'"

### ISSUE THREAD

**Issue by evilaliv3** [indutny/elliptic#81]
Currently the library is failing on all version of internet explorer as shown by the browsertesting implementing in: https://github.com/indutny/elliptic/pull/80

The failing tests are on the ed25519 derivations and the error is: Object doesn't support property or method 'privBytes'.

![screenshot from 2016-03-22 17 27 31](https://cloud.githubusercontent.com/assets/217034/13961882/c7a6d9a4-f05e-11e5-930c-63f71566bd4c.png)

**Comment by indutny** [comment]
Interesting... What IE version is this? May I ask you to post some code-context from `unittests-bundle.js:10979`?

**Comment by evilaliv3** [comment]
it apply to all the internet explorer versions from 8 to 11 :(

the context is:
```
  function testFactory(i) {
    it('can compute correct a and A for secret: ' + i, function() {
      var test = derivations[i];
      var secret = utils.toArray(test.secret_hex, 'hex');
      var key = ed25519.keyFromSecret(secret);
      assert.equal(toHex(key.privBytes()), test.a_hex);
      var xRecovered = toHex(ed25519.encodeInt(
                             ed25519.decodePoint(key.pubBytes()).getX()));
      assert.equal(xRecovered, test.A_P.x);
      assert.equal(toHex(key.pubBytes()), test.A_hex);
    });
  }
```

seems so that the ```key = ed25519.keyFromSecret(secret);``` is not returning a correct object containing privBytes method.

**Comment by evilaliv3** [comment]
i think i'm near to the point;

```
cachedProperty(KeyPair, function pubBytes() {
  return this.eddsa.encodePoint(this.pub());
});
```

i'm thinking that the cachedProperty is not working on IE; possible?
```
function cachedProperty(obj, computer) {
  var name = computer.name;
  var key = '_' + name;
  obj.prototype[name] = function cachedProperty() {
    return this[key] !== undefined ? this[key] :
           this[key] = computer.call(this);
  };
}
```

if this was working in past i think that probably the bug has been inserted in this commit: https://github.com/indutny/elliptic/commit/49533ee51624b3ce59be115bffc0310a32680263

**Comment by indutny** [comment]
Probably the `.name` is empty?

**Comment by indutny** [comment]
Seems to be non-standard: http://stackoverflow.com/questions/6903762/function-name-not-supported-in-ie

**Comment by evilaliv3** [comment]
bingo!

**Comment by indutny** [comment]
Fix is coming in a bit.

**Comment by indutny** [comment]
The regression tests will come with your patch, though :cry:

**Comment by indutny** [comment]
May I ask you to give a try to d3049b8fe9e205950937661d714686c69277a50e ?

**Comment by indutny** [comment]
Thanks!

**Comment by evilaliv3** [comment]
K! going to rebase my patch on current master, this way recommitting i will test it in the cloud!

**Comment by evilaliv3** [comment]
verified that tha this bug is solved! thanks to you!

**Comment by indutny** [comment]
no problem!
