### ISSUE TITLE
IE 8 is failing with "Object doesn't support this property or method"

### ISSUE THREAD

**Issue by evilaliv3** [indutny/elliptic#82]
Object does not support this proerty or method at line 9534 of the unittest-bundle.

![screenshot from 2016-03-23 02 42 35](https://cloud.githubusercontent.com/assets/217034/13973228/fe639c24-f0a0-11e5-9691-49f74af492eb.png)

the line is the map function called on array.

```
sha512_K = sha512_K.map(function(pair) {
  return new Num64(pair[0], pair[1]);
});
```

@indutny this function is supported only starting from IE9:
 https://stackoverflow.com/questions/12491444/javascript-map-method-creating-object-doesnt-support-this-property-or-method

**Comment by indutny** [comment]
Oh gosh... Do we really need to support this? It brings up the memories of 2010...

**Comment by evilaliv3** [comment]
the aim of your library is that, so i would say yes.

for myself i'm for using only browsers that support a good WebCrypto or better not use a browser when possible! :)

**Comment by indutny** [comment]
Could it be used with some ES5 polyfill instead? Or is this option not acceptable?

**Comment by evilaliv3** [comment]
yep i think so: https://github.com/es-shims/es5-shim/blob/master/es5-shim.js

map is added for exaple.

related: https://github.com/lhorie/mithril.js/issues/239

**Comment by indutny** [comment]
So, do you think it is an acceptable option for openpgpjs?

**Comment by evilaliv3** [comment]
i think so, obviously as last resort where webcrypto is not available.

**Comment by indutny** [comment]
Yeah, exactly! Closing the issue then!

**Comment by evilaliv3** [comment]
ah; you mean closing without adding the IE5shim to the library?

eventually document it on the readme as know issue and remove IE<9 from the codeclimate testing.

**Comment by indutny** [comment]
Yeah, this is what I meant. Sorry for confusion!

**Comment by indutny** [comment]
I agree that it can be documented indeed.
