### ISSUE TITLE
EdDSA: KeyPair.fromSecret

### ISSUE THREAD

**Issue by fanatid** [indutny/elliptic#83]
only [parseBytes](https://github.com/indutny/elliptic/blob/d3049b8fe9e205950937661d714686c69277a50e/lib/elliptic/eddsa/key.js#L20) now
`secret` shouldn't be more than `curve order`, am I right?

`elliptic curve` contain umod: https://github.com/indutny/elliptic/blob/d3049b8fe9e205950937661d714686c69277a50e/lib/elliptic/ec/key.js#L79

**Comment by indutny** [comment]
It shouldn't hurt to add `mod` there as well. Thanks for finding it!

**Comment by fanatid** [comment]
I rechecked `elliptic` code, `_secret` is not `privateKey`, it is a seed bytes.
@indutny it's part of `EdDSA`? I'm not familiar with this (definitely should read in depth).
