### ISSUE TITLE
Google Closure Support

### ISSUE THREAD

**Issue by xcthulhu** [indutny/elliptic#84]
I've been trying to do browser cryptography with ClojureScript, which leans on the Google Closure compiler for dead code removal.  I've been using BitPay's [BitAuth](https://github.com/bitpay/bitauth), which has elliptic as an upstream dependency (albeit version 1.0.0 according to their [package.json](https://github.com/bitpay/bitauth/blob/master/package.json#L34)).

I've been having some issues with the Google Closure compiler and elliptic, has this been resolved in later versions?

**Comment by indutny** [comment]
Hello!

Honestly saying, I don't really know. What kind of problems are you experiencing?

**Comment by xcthulhu** [comment]
Right now, I'm struggling to make an [externs file](https://developers.google.com/closure/compiler/docs/api-tutorial3) ([this](http://www.dotnetwise.com/code/externs/) automated tool chokes on elliptic).

I can write one from hand but I'll want to run it through your unit tests.

**Comment by indutny** [comment]
Oh well... I see it now, however there is nothing like this in the most recent version of elliptic. Of course I would be more than glad if you will submit a PR for adding this kind of metadata to the repo!

**Comment by indutny** [comment]
Closing this, nothing actionable on my side.
