### ISSUE TITLE
Q: What is the correct way to load an ECDSA secret key?

### ISSUE THREAD

**Issue by zsck** [indutny/elliptic#85]
Hi, I've just got a question for you that I'd like to ask now while I'm reading through source code and experimenting a little bit.

I'd like to sign some message using the `p384` curve and a secret key I have been provided for testing purposes.  The key is being given to me in Base64-DER-encoded format.  It was produced with the following Python code, which uses a [python-ecdsa](https://github.com/warner/python-ecdsa) library:

```py
def generate_ecdsa_pubkey(key_file_name, secret_key_dir='.'):
    sk = SigningKey.generate(curve=NIST384p)
    vk = sk.get_verifying_key()
    f = open(os.sep.join([secret_key_dir, key_file_name]), 'w')
    f.write(base64.standard_b64encode(sk.to_der()))
    f.close()
    return base64.standard_b64encode(vk.to_der())
```

Please note that this is not a security critical scenario- these keys and the signatures produced with them are *only* being used for local testing and will not be used in production.

Am I correct in thinking that I can obtain a key which will be capable of signing a buffer of data using the following?

```js
const EC = require('elliptic').ec
const ec = new EC('p384')
const key = ec.keyFromPrivate(new Buffer(loadedSecretKeyString), 64)
const signature = key.sign(new Buffer(stringMessage))
```

Could there perhaps be some documentation written in the repository to properly explain how to load keys from files, to ease use of this library by other developers in the future?

Thanks!

**Comment by indutny** [comment]
Hello!

From a quick look at the python library it looks like the `to_der` exports ASN.1 decoded private key using following schema:

```
SEQ([int(1), octetstring(privkey),cont[0], oid(secp224r1),
          cont[1],bitstring])
```

Where first bitstring is a private key itself, and the last one is the encoded public key (which you don't really need here).

I believe that you may want to first decode the `base64` data with:

```js
const unbase64 = new Buffer(loadedSecretKeyString, 'base64');
```

Then use some asn1 parser (like [asn1.js][0]) to decode it:

```
const PythonKey = asn1.define(function() {
  this.seq().obj(
    this.key('version').int(),
    this.key('private').octstr(),
    this.key('algorithm').explicit(0).oid(),
    this.key('public').explicit(1).bitstr()
  );
});

const key = PythonKey.decode(unbase64, 'der');

console.log(key.private);
```

Hopefully this will help!

Thanks,
Fedor.

[0]: https://github.com/indutny/asn1.js

**Comment by fanatid** [comment]
@indutny label ![screenshot at 2016-04-25 22 30 22](https://cloud.githubusercontent.com/assets/2633065/14796300/b52f043c-0b3d-11e6-8226-557daf8f3b69.png) will better than `Q` ;)

**Comment by indutny** [comment]
@fanatid done, but I don't think it really changes anything :)

**Comment by zsck** [comment]
This looks like it will answer my question perfectly. Thank you very much for the detailed response!
