### ISSUE TITLE
What does '04' in public key means?

### ISSUE THREAD

**Issue by hippich** [indutny/elliptic#86]
I noticed that when I do key.getPublic('hex') it gets prefixed with 0x04 byte. I also found that i can do key.getPublic(true, 'hex') to get 'compressed' version, which will not include 0x04 byte.

What 0x04 byte means?

**Comment by indutny** [comment]
This prefix represents the encoding of the public key:

* 0x04 - both x and y of the elliptic curve point follows
* 0x02,0x03 - only x follows (y is either odd or even depending on the prefix)

**Comment by hippich** [comment]
thanks!
