### ISSUE TITLE
missing dist folder in 6.2.3

### ISSUE THREAD

**Issue by rndme** [indutny/elliptic#87]
were "house builds" for browsers removed?

https://github.com/indutny/elliptic/blob/v6.2.2/dist/elliptic.min.js is the latest i can find.

seems a shame to have to download hundreds of megs of code and build it just to get a 100kb js file...

**Comment by fanatid** [comment]
`dist` folder was removed because it contained outdated file
What you offer? Build new file after each new version?

**Comment by indutny** [comment]
Should be fixed now. Thank you for report!

**Comment by fanatid** [comment]
@indutny you want update this files after every release?

**Comment by indutny** [comment]
@fanatid this will happen automatically on `npm version ...`

**Comment by fanatid** [comment]
I see, but what about repository? git saves only diff, but even with this.. size can be growth very quickly, I'm wrong?

**Comment by indutny** [comment]
@fanatid I suggest that we reconsider it a bit later. There weren't too much releases recently. If we will change the rate of releases - it will probably make sense to put dist files into a branch, but for now we should be safe.
