### ISSUE TITLE
Providing ecies_key_derivation request

### ISSUE THREAD

**Issue by jcalfee** [indutny/elliptic#9]
Is there anyway to plugin in a ECDH_compute_key method here:

https://github.com/indutny/elliptic/blob/master/test/ecdh-test.js

The openssl call `ECDH_compute_key` lets you put in a call back called `ecies_key_derivation`.  I need to somehow plug in that I would like to use a SHA512 hash in the key derivation (`derive`) method.

I think with a simple modification this could be done.  Can you please confirm?  I want to know I'm on the right track.

More information here:  http://stackoverflow.com/questions/26595085/computing-a-ecdh-shared-secret-in-javascript

Thank you...

**Comment by Kagami** [comment]
Hi. I wrote ECIES implementation using `elliptic` and `WebCryptoAPI`. You can see it here: https://github.com/bitchan/eccrypto/blob/cd217b2d026f152eecc702ba9cc83294167a8274/browser.js#L108-L136
Hope it helps.

**Comment by indutny** [comment]
This is implemented in 3rd party module. See README.md for details!
