### ISSUE TITLE
Support openssl's "hybrid" pubkey encoding.

### ISSUE THREAD

**Issue by chjj** [indutny/elliptic#91]
I was running the bitcoind script unit tests today with elliptic, and I noticed a few tests failing. It looks like they use openssl's little-known "hybrid" key format. Pieter Wuille [describes them here][1] after it was discovered that bitcoind inadvertently supported them by using openssl.

This is important for bitcoin consensus code since someone can fork a node that doesn't support hybrid pubkeys. They can also fork it in reverse with a CHECKSIG NOT -- causing the node that doesn't support hybrid keys to accept a transaction which uses them, whereas the rest of the network would reject it.

Example:

``` js
var elliptic = require('elliptic').ec('secp256k1');
var secp256k1 = require('secp256k1');

var msg = 'e1f1e44b57ce828a7e005a78788a1e4c67d93511af64ace51c861097b26c5788';
var sig = '3044022057292e2d4dfe775becdd0a9e6547997c728cdf35390f6a017da56d654d374e4902206b643be2fc53763b4e284845bfea2c597d2dc7759941dce937636c9d341b71ed';
var key = '0679be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8';

msg = new Buffer(msg, 'hex');
sig = new Buffer(sig, 'hex');
key = new Buffer(key, 'hex');

console.log(elliptic.verify(msg, sig, key)); // Throws with "Unknown point format"
console.log(secp256k1.verify(msg, secp256k1.signatureImport(sig), key)); // true
```

These are the signatures currently failing verification with elliptic:

```
msg: e1f1e44b57ce828a7e005a78788a1e4c67d93511af64ace51c861097b26c5788
sig: 3044022057292e2d4dfe775becdd0a9e6547997c728cdf35390f6a017da56d654d374e4902206b643be2fc53763b4e284845bfea2c597d2dc7759941dce937636c9d341b71ed
key: 0679be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8
```

```
msg: a79c1cd8519d094995905a6aeb62d3af1d1e3cef8d4089e55e8a19788ee5b024
sig: 30440220035d554e3153c14950c9993f41c496607a8e24093db0595be7bf875cf64fcf1f02204731c8c4e5daf15e706cec19cdd8f2c5b1d05490e11dab8465ed426569b6e921
key: 0679be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8
```

[1]: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2012-June/001578.html

**Comment by chjj** [comment]
I've added this to my own code, but it's pretty ugly:

``` js
    ...

    if (key[0] === 0x06 || key[0] === 0x07) {
      hybrid = key[0];
      key[0] = 0x04;
    }

    result = elliptic.verify(msg, sig, key);

    if (hybrid)
      key[0] = hybrid;

    return result;
```

**Comment by indutny** [comment]
Should be fixed now.

**Comment by ifrahQ** [comment]
Hey!
Even I am getting the below error while running the code. Any help would be highly appreciated.
Error: Unknown point format
    at ShortCurve.decodePoint (/home/runner/node_modules/elliptic/lib/elliptic/curve/base.js:285:9)
    at KeyPair._importPublic (/home/runner/node_modules/elliptic/lib/elliptic/ec/key.js:99:28)
    at new KeyPair (/home/runner/node_modules/elliptic/lib/elliptic/ec/key.js:17:10)
    at Function.fromPublic (/home/runner/node_modules/elliptic/lib/elliptic/ec/key.js:25:10)
    at EC.keyFromPublic (/home/runner/node_modules/elliptic/lib/elliptic/ec/index.js:50:18)
    at evalmachine.<anonymous>:21:31
    at Script.runInContext (vm.js:107:20)
    at Object.runInContext (vm.js:285:6)
    at evaluate (/run_dir/repl.js:133:14)
    at ReadStream.<anonymous> (/run_dir/repl.js:116:5)
