### ISSUE TITLE
p192 (elliptic, node.js) versus prime192v1 (BouncyCastle, Java)

### ISSUE THREAD

**Issue by dwimberger** [indutny/elliptic#97]
Is there a difference between p192 and prime192v1? Respectively, is there a way to match the node.js version to the prime192v1 changing parameters?

Note: to match the hashing , I have changed the Hash Algorithm to sha1 in curves.js

    hash: hash.sha1,

Doing the verification in node.js:

    Buffer.prototype.toByteArray = function () { 
      return Array.prototype.slice.call(this, 0); 
    }
    var data = new Buffer('464756473244334D5836304A4754504D53304D51', 'hex').toByteArray();

    var hexCardPublic = '0499A84E4ADC581DB12CDD2D04EC8944BF88DFA24C4709ABBE1A3E1668C4F6BDA3CE6DFD0050F3085A2332D21FF53DDB21';
    var publicKey = new Buffer(hexCardPublic, 'hex').toByteArray();

    var signature = '3036021900C031D6ED904442C600430B1500EB9D8C55110FE10763A84002190089668A4EEC9640D1A897D0BDAA2B3976CDA6769AA74B8ABA';
    var signedData = new Buffer(signature, 'hex').toByteArray();
   
    var ec = new EC('p192');
    var pubKey = ec.keyFromPublic(publicKey);
    console.log(pubKey.verify(data, signedData));

Will result in 

     false

While doing the same with BouncyCastle (Java counterpart)

    byte[] publicKey = Hex.decode(
                    "0499A84E4ADC581DB12CDD2D04EC8944BF88DFA24C4709ABBE1A3E1668C4F6BDA3CE6DFD0050F3085A2332D21FF53DDB21"
            );
    byte[] signedData = Hex.decode(
                    "3036021900C031D6ED904442C600430B1500EB9D8C55110FE10763A84002190089668A4EEC9640D1A897D0BDAA2B3976CDA6769AA74B8ABA"
            );
    byte[] data = Hex.decode(
                    "464756473244334D5836304A4754504D53304D51"
            );

            ECParameterSpec params = ECNamedCurveTable.getParameterSpec("prime192v1");

            KeyFactory keyFactory = KeyFactory.getInstance("EC", "BC");
            ECPublicKeySpec pubKeySpec = new ECPublicKeySpec(
                    params.getCurve().decodePoint(publicKey),
                    params
            );
            PublicKey pubKey = keyFactory.generatePublic(pubKeySpec);
            Signature signature = Signature.getInstance("ECDSA", "BC");
            signature.initVerify(pubKey);
            signature.update(data);
            System.out.println(signature.verify(signedData));

Will return 

    true

**Comment by indutny** [comment]
Thank you for reporting this!

Elliptic does not hash the message by itself. The application that calls `.verify()` is responsible for hashing the message with appropriate hash function.

Here is a code sample that works:

```js
var BN = require('bn.js');
var crypto = require('crypto');
var elliptic = require('elliptic');

Buffer.prototype.toByteArray = function () { 
  return Array.prototype.slice.call(this, 0); 
}
var data = new Buffer('464756473244334D5836304A4754504D53304D51', 'hex');
var hashed = crypto.createHash('sha1').update(data).digest().toByteArray();

var hexCardPublic = '0499A84E4ADC581DB12CDD2D04EC8944BF88DFA24C4709ABBE1A3E1668C4F6BDA3CE6DFD0050F3085A2332D21FF53DDB21';
var publicKey = new Buffer(hexCardPublic, 'hex').toByteArray();

var signature = '3036021900C031D6ED904442C600430B1500EB9D8C55110FE10763A84002190089668A4EEC9640D1A897D0BDAA2B3976CDA6769AA74B8ABA';
var signedData = new Buffer(signature, 'hex').toByteArray();

var ec = new elliptic.ec('p192');
var pubKey = ec.keyFromPublic(publicKey);
console.log(pubKey.verify(hashed, signedData));
```

**Comment by dwimberger** [comment]
Thanks for your speed-of-light reply :)
Indeed it works. 

Sorry, I thought that the hashing step was part of the ECDSA algorithm.

Is there an impact the other way around also (i.e. sign() with elliptic; hashing required? and verify() with bouncycastle).

**Comment by indutny** [comment]
Yep, hashing is required everywhere where you pass message. `elliptic` uses hashing only for its pseudo-random number generator.
