### ISSUE TITLE
curve25519 import/export mismatch

### ISSUE THREAD

**Issue by mvayngrib** [indutny/elliptic#98]
i was exploring a compatibility issue with [tweetnacl-js](https://github.com/dchest/tweetnacl-js) and am seeing some weird behavior

``` js
var nacl = require('tweetnacl')
var ec = require('elliptic').ec('curve25519')
// priv keys don't match
// var privBuf = new Buffer(nacl.box.keyPair().secretKey)
// priv keys match
var privBuf = new Buffer(ec.genKeyPair().getPrivate('hex'), 'hex')
var naclKey = nacl.box.keyPair.fromSecretKey(privBuf)
var ellipticKey = ec.keyFromPrivate(privBuf, 'hex')
console.log('priv original', privBuf.toString('hex'))
console.log('priv nacl    ', new Buffer(naclKey.secretKey).toString('hex'))
console.log('priv elliptic', ellipticKey.getPrivate('hex'))
// pub keys never match
console.log('pub nacl     ', new Buffer(naclKey.publicKey).toString('hex'))
console.log('pub elliptic ', ellipticKey.getPublic(true, 'hex'))
```

after experimenting bit, i noticed that sometimes importing and re-exporting elliptic doesn't export the same private key as it imports:

``` js
// import and re-export key doesn't produce the same value
var ec = require('elliptic').ec('curve25519')
// I generated the following key with: nacl.box.keyPair().secretKey
ec.keyFromPrivate('7d8bdc26d9696f9ae92592031a6eeeec7501b72681276d05203f6fab26848e6d', 'hex').getPrivate('hex')
// prints: 0d8bdc26d9696f9ae92592031a6eeeebe2e8e2100c622328b7beb9f29bcbc2f2
```

any idea what's going on?

**Comment by fanatid** [comment]
`7d8bdc26d9696f9ae92592031a6eeeec7501b72681276d05203f6fab26848e6d` imported as `0d8bdc26d9696f9ae92592031a6eeeebe2e8e2100c622328b7beb9f29bcbc2f2` because private key truncated by `n` (`1000000000000000000000000000000014def9dea2f79cd65812631a5cf5d3ed`)

**Comment by mvayngrib** [comment]
@fanatid thx for the quick response. And do you know the reason for the difference in exported public keys?

**Comment by fanatid** [comment]
@mvayngrib idk right now, but I hope @indutny has explanation

**Comment by fanatid** [comment]
ping @dchest

**Comment by dchest** [comment]
Unfortunately, I don't know what's going on. Does this package [clear appropriate bits](https://github.com/dchest/tweetnacl-js/blob/master/nacl.js#L392) from secret key?

**Comment by indutny** [comment]
cc @sublimator 

Will take a look at this later today.

**Comment by indutny** [comment]
Whoa, I felt some deja vu about this, and I [was right this time][0].

Basically, the way `curve25519` is implemented by DJB is that the bytes are reversed (plus some bit fiddling). Here is a code sample that works:

```js
var nacl = require('tweetnacl')
var ec = require('elliptic').ec('curve25519')
// priv keys don't match
// var privBuf = new Buffer(nacl.box.keyPair().secretKey)
// priv keys match
var privBuf = new Buffer(ec.genKeyPair().getPrivate('hex'), 'hex')
var naclKey = nacl.box.keyPair.fromSecretKey(privBuf)

var eprivBuf = new Buffer(32);
for (var i = 0; i < 32; i++)
  eprivBuf[i] = privBuf[32 - i - 1];
eprivBuf[31] &= 248
eprivBuf[0] &= 127
eprivBuf[0] |= 64

var ellipticKey = ec.keyFromPrivate(eprivBuf, 'hex')
console.log('priv original', privBuf.toString('hex'))
console.log('priv nacl    ', new Buffer(naclKey.secretKey).toString('hex'))
console.log('priv elliptic', ellipticKey.getPrivate('hex'))
// pub keys never match
console.log('pub nacl     ', new Buffer(naclKey.publicKey).toString('hex'))
var pub = new Buffer(ellipticKey.getPublic(true, 'hex'), 'hex');
var revPub = new Buffer(32);
for (var i = 0; i < pub.length; i++)
  revPub[i] = pub[32 - i - 1];
console.log('pub elliptic', revPub.toString('hex'));
```

We should probably make an API for this someday.

[0]: https://github.com/indutny/elliptic/issues/23#issuecomment-70671810

**Comment by indutny** [comment]
NOTE: that code sample sometimes crashes, but that's because `privBuf` is fed to the tweetnacl, it actually expects it in reverse.

**Comment by mvayngrib** [comment]
@indutny thanks for explaining! Could you comment on the rationale between the difference in implementation? Is one more standard than the other?

**Comment by indutny** [comment]
@mvayngrib I'd say elliptic.js implementation is more generic, that will work with various Montgomery curves. While the one in curve25519 is really specific to curve25519 itself.

No other reason, really.

**Comment by mvayngrib** [comment]
@indutny hm, clearing those bits seems...very purposeful :)

**Comment by indutny** [comment]
I'm not saying it is not, I wouldn't mind if someone will contribute proper APIs for this thing.

**Comment by indutny** [comment]
Maybe as a third-party npm module, though

**Comment by grinsekatze003** [comment]
I'm using `getPublic(false, false)´ to retrieve public key as a non encoded point (X,Y). How do I have to apply these bit rotations / reversing to "fix" the returned coordinates so that they match with tweetnacl?

**Comment by grinsekatze003** [comment]
@indutny I'm using `getPublic(false, false)´ to retrieve public key as a non encoded point (X,Y). How do I have to apply these bit rotations / reversing to "fix" the returned coordinates so that they match with tweetnacl?

**Comment by indutny** [comment]
@grinsekatze003 this is not a bit rotations, but byte rotations.

**Comment by grinsekatze003** [comment]
@indutny Sorry, I did mean byte rotation. Do you know how to apply them so that public key point (X,Z) is correct?

**Comment by indutny** [comment]
@grinsekatze003 have you seen https://github.com/indutny/elliptic/issues/23#issuecomment-70671810 ?

**Comment by grinsekatze003** [comment]
@indutny Yes I have, but I don't know if it can help. I'm using your code (https://github.com/indutny/elliptic/issues/98#issuecomment-238155817) right now and I've added `console.log(ellipticKey.getPublic(false, false))` to the bottom. It gives me X and Y coordinate of EC point, but I think they are wrong because the byte rotation operations are missing. Is this correct? If so, can you lead me in the right direction how to fix this?

**Comment by indutny** [comment]
@grinsekatze003 why do you need a `z` from the point? I think `ellipticKey.getPublic()` is an API that you are looking for. It should be pretty straightforward to reverse the bytes of the resulting Buffer using examples above.

**Comment by grinsekatze003** [comment]
I need X and Z because I'm doing further calculations using these coordinates (similar to ECDH). Yes, if I do  `ellipticKey.getPublic(true)` to get public key as a buffer, it is pretty straightforward. But if I do `ellipticKey.getPublic(false)` I get the X and Z coordinates and I have no idea how to reverse them.. Do you know what I mean?

**Comment by indutny** [comment]
@grinsekatze003 not really, sorry! `X` is enough to do further any calculations, because `Z` is used internally just for performance reasons.

If you'd share more of what you try to accomplish, I may be able to help. I don't see why they should be reversed from your comments above.
